mutation Login($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    accessToken
    user {
      id
      username
      quotaBytes
      usedBytes
      isAdmin
    }
  }
}

mutation Register($username: String!, $password: String!) {
  register(username: $username, password: $password) {
    accessToken
    user {
      id
      username
      quotaBytes
      usedBytes
      isAdmin
    }
  }
}

mutation Refresh {
  refresh {
    accessToken
    user {
      id
      username
      quotaBytes
      usedBytes
      isAdmin
    }
  }
}

mutation Logout {
  logout
}

query Me {
  me {
    id
    username
    quotaBytes
    usedBytes
    isAdmin
  }
}

mutation ChangePassword($oldPassword: String!, $newPassword: String!) {
  changePassword(oldPassword: $oldPassword, newPassword: $newPassword) {
    accessToken
    user {
      id
      username
      quotaBytes
      usedBytes
      isAdmin
    }
  }
}
