// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_passwords.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAppPassword = `-- name: CreateAppPassword :one
INSERT INTO app_passwords (id, user_id, name, token_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, token_hash, created_at, last_used_at
`

type CreateAppPasswordParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	TokenHash string
}

func (q *Queries) CreateAppPassword(ctx context.Context, arg CreateAppPasswordParams) (AppPassword, error) {
	row := q.db.QueryRow(ctx, createAppPassword,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
	)
	var i AppPassword
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteAppPassword = `-- name: DeleteAppPassword :execrows
DELETE FROM app_passwords WHERE id = $1 AND user_id = $2
`

type DeleteAppPasswordParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAppPassword(ctx context.Context, arg DeleteAppPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppPassword, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppPasswordByHash = `-- name: GetAppPasswordByHash :one
SELECT ap.id, ap.user_id, ap.name, ap.token_hash, ap.created_at, ap.last_used_at, u.username, (u.disabled_at IS NOT NULL)::boolean AS owner_disabled
FROM app_passwords ap JOIN users u ON u.id = ap.user_id
WHERE ap.token_hash = $1
`

type GetAppPasswordByHashRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          string
	TokenHash     string
	CreatedAt     pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
	Username      string
	OwnerDisabled bool
}

// 认证主路径:带出属主的禁用状态与用户名,一次查询定乾坤
func (q *Queries) GetAppPasswordByHash(ctx context.Context, tokenHash string) (GetAppPasswordByHashRow, error) {
	row := q.db.QueryRow(ctx, getAppPasswordByHash, tokenHash)
	var i GetAppPasswordByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Username,
		&i.OwnerDisabled,
	)
	return i, err
}

const listAppPasswords = `-- name: ListAppPasswords :many
SELECT id, user_id, name, token_hash, created_at, last_used_at FROM app_passwords WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAppPasswords(ctx context.Context, userID uuid.UUID) ([]AppPassword, error) {
	rows, err := q.db.Query(ctx, listAppPasswords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppPassword
	for rows.Next() {
		var i AppPassword
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAppPassword = `-- name: TouchAppPassword :exec
UPDATE app_passwords SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

// last_used_at 五分钟才写一次,别让 rclone 的请求风暴变成写风暴
func (q *Queries) TouchAppPassword(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAppPassword, id)
	return err
}
