// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addUsedBytes = `-- name: AddUsedBytes :exec
UPDATE users SET used_bytes = used_bytes + $2 WHERE id = $1
`

type AddUsedBytesParams struct {
	ID        uuid.UUID
	UsedBytes int64
}

func (q *Queries) AddUsedBytes(ctx context.Context, arg AddUsedBytesParams) error {
	_, err := q.db.Exec(ctx, addUsedBytes, arg.ID, arg.UsedBytes)
	return err
}

const deleteBlob = `-- name: DeleteBlob :exec
DELETE FROM blobs WHERE id = $1
`

func (q *Queries) DeleteBlob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlob, id)
	return err
}

const getBlob = `-- name: GetBlob :one
SELECT id, sha256, size, mime, ref_count, verified, media_meta, created_at, deref_at FROM blobs WHERE id = $1
`

func (q *Queries) GetBlob(ctx context.Context, id uuid.UUID) (Blob, error) {
	row := q.db.QueryRow(ctx, getBlob, id)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.Size,
		&i.Mime,
		&i.RefCount,
		&i.Verified,
		&i.MediaMeta,
		&i.CreatedAt,
		&i.DerefAt,
	)
	return i, err
}

const getBlobBySha256 = `-- name: GetBlobBySha256 :one
SELECT id, sha256, size, mime, ref_count, verified, media_meta, created_at, deref_at FROM blobs WHERE sha256 = $1
`

func (q *Queries) GetBlobBySha256(ctx context.Context, sha256 string) (Blob, error) {
	row := q.db.QueryRow(ctx, getBlobBySha256, sha256)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.Size,
		&i.Mime,
		&i.RefCount,
		&i.Verified,
		&i.MediaMeta,
		&i.CreatedAt,
		&i.DerefAt,
	)
	return i, err
}

const getBlobSizes = `-- name: GetBlobSizes :many
SELECT id, size FROM blobs WHERE id = ANY($1::uuid[])
`

type GetBlobSizesRow struct {
	ID   uuid.UUID
	Size int64
}

func (q *Queries) GetBlobSizes(ctx context.Context, dollar_1 []uuid.UUID) ([]GetBlobSizesRow, error) {
	rows, err := q.db.Query(ctx, getBlobSizes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlobSizesRow
	for rows.Next() {
		var i GetBlobSizesRow
		if err := rows.Scan(&i.ID, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementBlobRef = `-- name: IncrementBlobRef :exec
UPDATE blobs SET ref_count = ref_count + 1, deref_at = NULL WHERE id = $1
`

func (q *Queries) IncrementBlobRef(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementBlobRef, id)
	return err
}

const listGCableBlobs = `-- name: ListGCableBlobs :many
SELECT id, sha256, size, mime, ref_count, verified, media_meta, created_at, deref_at FROM blobs
WHERE ref_count = 0 AND deref_at IS NOT NULL AND deref_at < now() - interval '24 hours'
LIMIT 100
`

func (q *Queries) ListGCableBlobs(ctx context.Context) ([]Blob, error) {
	rows, err := q.db.Query(ctx, listGCableBlobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blob
	for rows.Next() {
		var i Blob
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.Size,
			&i.Mime,
			&i.RefCount,
			&i.Verified,
			&i.MediaMeta,
			&i.CreatedAt,
			&i.DerefAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByBlob = `-- name: ListNodesByBlob :many
SELECT id, owner_id, parent_id, name, kind, blob_id, deleted_at, created_at, updated_at, subtree_bytes, subtree_count, stats_stale FROM nodes WHERE blob_id = $1
`

func (q *Queries) ListNodesByBlob(ctx context.Context, blobID *uuid.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodesByBlob, blobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBlobVerified = `-- name: MarkBlobVerified :exec
UPDATE blobs SET verified = true WHERE id = $1
`

func (q *Queries) MarkBlobVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBlobVerified, id)
	return err
}

const sumBlobSizes = `-- name: SumBlobSizes :one
SELECT COALESCE(sum(size), 0)::bigint AS total FROM blobs WHERE id = ANY($1::uuid[])
`

func (q *Queries) SumBlobSizes(ctx context.Context, dollar_1 []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumBlobSizes, dollar_1)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const upsertBlob = `-- name: UpsertBlob :one
INSERT INTO blobs (id, sha256, size, mime)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sha256) DO UPDATE SET sha256 = EXCLUDED.sha256
RETURNING id, sha256, size, mime, ref_count, verified, media_meta, created_at, deref_at
`

type UpsertBlobParams struct {
	ID     uuid.UUID
	Sha256 string
	Size   int64
	Mime   string
}

// 并发同 hash 上传竞争时收敛到同一行
func (q *Queries) UpsertBlob(ctx context.Context, arg UpsertBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, upsertBlob,
		arg.ID,
		arg.Sha256,
		arg.Size,
		arg.Mime,
	)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.Size,
		&i.Mime,
		&i.RefCount,
		&i.Verified,
		&i.MediaMeta,
		&i.CreatedAt,
		&i.DerefAt,
	)
	return i, err
}
