// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertChatMessage = `-- name: InsertChatMessage :one
INSERT INTO chat_messages (id, owner_id, body, node_id)
VALUES ($1, $2, $3, $4) RETURNING id, owner_id, body, node_id, created_at
`

type InsertChatMessageParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Body    string
	NodeID  *uuid.UUID
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, insertChatMessage,
		arg.ID,
		arg.OwnerID,
		arg.Body,
		arg.NodeID,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.NodeID,
		&i.CreatedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, owner_id, body, node_id, created_at
FROM chat_messages
WHERE owner_id = $1
ORDER BY id DESC
LIMIT $2
`

type ListChatMessagesParams struct {
	OwnerID uuid.UUID
	Limit   int32
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessages, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Body,
			&i.NodeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessagesBefore = `-- name: ListChatMessagesBefore :many
SELECT id, owner_id, body, node_id, created_at
FROM chat_messages
WHERE owner_id = $1 AND id < $2
ORDER BY id DESC
LIMIT $3
`

type ListChatMessagesBeforeParams struct {
	OwnerID uuid.UUID
	ID      uuid.UUID
	Limit   int32
}

// last_id 游标:uuid v7 时间有序, id < last_id 取"更旧"的消息。
func (q *Queries) ListChatMessagesBefore(ctx context.Context, arg ListChatMessagesBeforeParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessagesBefore, arg.OwnerID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Body,
			&i.NodeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readUserChatFolderID = `-- name: ReadUserChatFolderID :one
SELECT chat_folder_id FROM users WHERE id = $1
`

func (q *Queries) ReadUserChatFolderID(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, readUserChatFolderID, id)
	var chat_folder_id *uuid.UUID
	err := row.Scan(&chat_folder_id)
	return chat_folder_id, err
}

const setUserChatFolderID = `-- name: SetUserChatFolderID :exec
UPDATE users SET chat_folder_id = $2 WHERE id = $1
`

type SetUserChatFolderIDParams struct {
	ID           uuid.UUID
	ChatFolderID *uuid.UUID
}

func (q *Queries) SetUserChatFolderID(ctx context.Context, arg SetUserChatFolderIDParams) error {
	_, err := q.db.Exec(ctx, setUserChatFolderID, arg.ID, arg.ChatFolderID)
	return err
}
