// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: derivatives.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getDerivatives = `-- name: GetDerivatives :many
SELECT blob_id, kind, minio_key, size, created_at FROM derivatives WHERE blob_id = $1
`

func (q *Queries) GetDerivatives(ctx context.Context, blobID uuid.UUID) ([]Derivative, error) {
	rows, err := q.db.Query(ctx, getDerivatives, blobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Derivative
	for rows.Next() {
		var i Derivative
		if err := rows.Scan(
			&i.BlobID,
			&i.Kind,
			&i.MinioKey,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, kind, blob_id, status, attempts, last_error, created_at, updated_at FROM tasks WHERE kind = $1 AND blob_id = $2
`

type GetTaskParams struct {
	Kind   string
	BlobID uuid.UUID
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.Kind, arg.BlobID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.BlobID,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setBlobMediaMeta = `-- name: SetBlobMediaMeta :exec
UPDATE blobs SET media_meta = $2 WHERE id = $1
`

type SetBlobMediaMetaParams struct {
	ID        uuid.UUID
	MediaMeta []byte
}

func (q *Queries) SetBlobMediaMeta(ctx context.Context, arg SetBlobMediaMetaParams) error {
	_, err := q.db.Exec(ctx, setBlobMediaMeta, arg.ID, arg.MediaMeta)
	return err
}

const upsertDerivative = `-- name: UpsertDerivative :exec
INSERT INTO derivatives (blob_id, kind, minio_key, size)
VALUES ($1, $2, $3, $4)
ON CONFLICT (blob_id, kind) DO UPDATE SET minio_key = EXCLUDED.minio_key, size = EXCLUDED.size
`

type UpsertDerivativeParams struct {
	BlobID   uuid.UUID
	Kind     string
	MinioKey string
	Size     int64
}

func (q *Queries) UpsertDerivative(ctx context.Context, arg UpsertDerivativeParams) error {
	_, err := q.db.Exec(ctx, upsertDerivative,
		arg.BlobID,
		arg.Kind,
		arg.MinioKey,
		arg.Size,
	)
	return err
}
