// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_tokens.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMCPToken = `-- name: CreateMCPToken :one
INSERT INTO mcp_tokens (id, user_id, name, token_hash, scopes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, scopes, created_at, last_used_at, revoked_at
`

type CreateMCPTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	TokenHash string
	Scopes    []string
}

func (q *Queries) CreateMCPToken(ctx context.Context, arg CreateMCPTokenParams) (McpToken, error) {
	row := q.db.QueryRow(ctx, createMCPToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Scopes,
	)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getMCPTokenByHash = `-- name: GetMCPTokenByHash :one
SELECT mt.id, mt.user_id, mt.name, mt.token_hash, mt.scopes, mt.created_at, mt.last_used_at, mt.revoked_at, u.username, (u.disabled_at IS NOT NULL)::boolean AS owner_disabled
FROM mcp_tokens mt JOIN users u ON u.id = mt.user_id
WHERE mt.token_hash = $1 AND mt.revoked_at IS NULL
`

type GetMCPTokenByHashRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          string
	TokenHash     string
	Scopes        []string
	CreatedAt     pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	Username      string
	OwnerDisabled bool
}

func (q *Queries) GetMCPTokenByHash(ctx context.Context, tokenHash string) (GetMCPTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getMCPTokenByHash, tokenHash)
	var i GetMCPTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Username,
		&i.OwnerDisabled,
	)
	return i, err
}

const listMCPTokens = `-- name: ListMCPTokens :many
SELECT id, user_id, name, token_hash, scopes, created_at, last_used_at, revoked_at FROM mcp_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListMCPTokens(ctx context.Context, userID uuid.UUID) ([]McpToken, error) {
	rows, err := q.db.Query(ctx, listMCPTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpToken
	for rows.Next() {
		var i McpToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMCPToken = `-- name: RevokeMCPToken :execrows
UPDATE mcp_tokens SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeMCPTokenParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeMCPToken(ctx context.Context, arg RevokeMCPTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMCPToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchMCPToken = `-- name: TouchMCPToken :exec
UPDATE mcp_tokens SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

func (q *Queries) TouchMCPToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchMCPToken, id)
	return err
}
