// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppPassword struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	TokenHash  string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type Blob struct {
	ID        uuid.UUID
	Sha256    string
	Size      int64
	Mime      string
	RefCount  int32
	Verified  bool
	MediaMeta []byte
	CreatedAt pgtype.Timestamptz
	DerefAt   pgtype.Timestamptz
}

type Derivative struct {
	BlobID    uuid.UUID
	Kind      string
	MinioKey  string
	Size      int64
	CreatedAt pgtype.Timestamptz
}

type McpToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	TokenHash  string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Node struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
}

type OauthAccessToken struct {
	ID         uuid.UUID
	GrantID    uuid.UUID
	TokenHash  string
	Scopes     []string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type OauthAuthorizationCode struct {
	CodeHash      string
	GrantID       uuid.UUID
	ClientID      string
	RedirectUri   string
	Scopes        []string
	CodeChallenge string
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type OauthClient struct {
	ClientID     string
	ClientName   string
	RedirectUris []string
	CreatedAt    pgtype.Timestamptz
}

type OauthGrant struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ClientID  string
	Scopes    []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type OauthRefreshToken struct {
	ID        uuid.UUID
	GrantID   uuid.UUID
	TokenHash string
	Scopes    []string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	FamilyID  uuid.UUID
	UsedAt    pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Share struct {
	ID           uuid.UUID
	Token        string
	NodeID       uuid.UUID
	CreatedBy    uuid.UUID
	PasswordHash *string
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Task struct {
	ID        uuid.UUID
	Kind      string
	BlobID    uuid.UUID
	Status    string
	Attempts  int32
	LastError *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TransferSession struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	TargetParent   *uuid.UUID
	TargetName     string
	Size           int64
	Mime           string
	ExpectedSha256 *string
	ComputedSha256 *string
	ObjectKey      string
	Transport      string
	MinioUploadID  *string
	PartSize       int32
	Status         string
	FailReason     *string
	NodeID         *uuid.UUID
	IdempotencyKey *string
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type UploadSession struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Sha256        string
	Size          int64
	TargetParent  *uuid.UUID
	TargetName    string
	MinioUploadID string
	PartSize      int32
	Status        string
	FailReason    *string
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	QuotaBytes   int64
	UsedBytes    int64
	IsAdmin      bool
	CreatedAt    pgtype.Timestamptz
	DisabledAt   pgtype.Timestamptz
}
