// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countChildren = `-- name: CountChildren :one
SELECT count(*) FROM nodes
WHERE owner_id = $1 AND parent_id IS NOT DISTINCT FROM $2 AND deleted_at IS NULL
`

type CountChildrenParams struct {
	OwnerID  uuid.UUID
	ParentID *uuid.UUID
}

func (q *Queries) CountChildren(ctx context.Context, arg CountChildrenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChildren, arg.OwnerID, arg.ParentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchNodes = `-- name: CountSearchNodes :one
SELECT count(*) FROM nodes
WHERE owner_id = $1 AND deleted_at IS NULL AND name ILIKE '%' || $2 || '%'
`

type CountSearchNodesParams struct {
	OwnerID uuid.UUID
	Column2 *string
}

func (q *Queries) CountSearchNodes(ctx context.Context, arg CountSearchNodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchNodes, arg.OwnerID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrash = `-- name: CountTrash :one
SELECT count(*) FROM nodes n
WHERE n.owner_id = $1 AND n.deleted_at IS NOT NULL
  AND (n.parent_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM nodes p WHERE p.id = n.parent_id AND p.deleted_at IS NOT NULL))
`

func (q *Queries) CountTrash(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTrash, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (id, owner_id, parent_id, name, kind, blob_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, parent_id, name, kind, blob_id, deleted_at, created_at, updated_at
`

type CreateNodeParams struct {
	ID       uuid.UUID
	OwnerID  uuid.UUID
	ParentID *uuid.UUID
	Name     string
	Kind     string
	BlobID   *uuid.UUID
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ID,
		arg.OwnerID,
		arg.ParentID,
		arg.Name,
		arg.Kind,
		arg.BlobID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementBlobRefs = `-- name: DecrementBlobRefs :exec
UPDATE blobs SET
    ref_count = ref_count - 1,
    deref_at  = CASE WHEN ref_count - 1 = 0 THEN now() ELSE deref_at END
WHERE id = ANY($1::uuid[])
`

func (q *Queries) DecrementBlobRefs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementBlobRefs, dollar_1)
	return err
}

const getActiveNodeOwned = `-- name: GetActiveNodeOwned :one
SELECT id, owner_id, parent_id, name, kind, blob_id, deleted_at, created_at, updated_at FROM nodes WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type GetActiveNodeOwnedParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetActiveNodeOwned(ctx context.Context, arg GetActiveNodeOwnedParams) (Node, error) {
	row := q.db.QueryRow(ctx, getActiveNodeOwned, arg.ID, arg.OwnerID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, owner_id, parent_id, name, kind, blob_id, deleted_at, created_at, updated_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeWithBlob = `-- name: GetNodeWithBlob :one
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256, b.verified AS blob_verified
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.id = $1 AND n.owner_id = $2
`

type GetNodeWithBlobParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

type GetNodeWithBlobRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
	BlobVerified *bool
}

func (q *Queries) GetNodeWithBlob(ctx context.Context, arg GetNodeWithBlobParams) (GetNodeWithBlobRow, error) {
	row := q.db.QueryRow(ctx, getNodeWithBlob, arg.ID, arg.OwnerID)
	var i GetNodeWithBlobRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlobSize,
		&i.BlobMime,
		&i.BlobSha256,
		&i.BlobVerified,
	)
	return i, err
}

const isDescendant = `-- name: IsDescendant :one
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
)
SELECT count(*) > 0 AS is_descendant
FROM nodes x
WHERE x.id = $2 AND x.id IN (SELECT s.id FROM sub s)
`

type IsDescendantParams struct {
	ID   uuid.UUID
	ID_2 uuid.UUID
}

// $2(candidate)是否在 $1(ancestor)的子树内(含自身)
func (q *Queries) IsDescendant(ctx context.Context, arg IsDescendantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDescendant, arg.ID, arg.ID_2)
	var is_descendant bool
	err := row.Scan(&is_descendant)
	return is_descendant, err
}

const listChildren = `-- name: ListChildren :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1
  AND n.parent_id IS NOT DISTINCT FROM $2
  AND n.deleted_at IS NULL
ORDER BY
  n.kind DESC, -- folder 在前
  CASE WHEN $3::text = 'NAME'       AND NOT $4::boolean THEN n.name END ASC,
  CASE WHEN $3::text = 'NAME'       AND     $4::boolean THEN n.name END DESC,
  CASE WHEN $3::text = 'SIZE'       AND NOT $4::boolean THEN b.size END ASC NULLS FIRST,
  CASE WHEN $3::text = 'SIZE'       AND     $4::boolean THEN b.size END DESC NULLS LAST,
  CASE WHEN $3::text = 'UPDATED_AT' AND NOT $4::boolean THEN n.updated_at END ASC,
  CASE WHEN $3::text = 'UPDATED_AT' AND     $4::boolean THEN n.updated_at END DESC,
  n.id
LIMIT $6 OFFSET $5
`

type ListChildrenParams struct {
	OwnerID    uuid.UUID
	ParentID   *uuid.UUID
	OrderBy    string
	Descending bool
	PageOffset int32
	PageLimit  int32
}

type ListChildrenRow struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	ParentID   *uuid.UUID
	Name       string
	Kind       string
	BlobID     *uuid.UUID
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	BlobSize   *int64
	BlobMime   *string
	BlobSha256 *string
}

func (q *Queries) ListChildren(ctx context.Context, arg ListChildrenParams) ([]ListChildrenRow, error) {
	rows, err := q.db.Query(ctx, listChildren,
		arg.OwnerID,
		arg.ParentID,
		arg.OrderBy,
		arg.Descending,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenRow
	for rows.Next() {
		var i ListChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrash = `-- name: ListTrash :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1 AND n.deleted_at IS NOT NULL
  -- 只列回收站顶层:父不存在、父未删,或父先于自己被单独删除后还原过
  AND (n.parent_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM nodes p WHERE p.id = n.parent_id AND p.deleted_at IS NOT NULL))
ORDER BY n.deleted_at DESC, n.id
LIMIT $2 OFFSET $3
`

type ListTrashParams struct {
	OwnerID uuid.UUID
	Limit   int32
	Offset  int32
}

type ListTrashRow struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	ParentID   *uuid.UUID
	Name       string
	Kind       string
	BlobID     *uuid.UUID
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	BlobSize   *int64
	BlobMime   *string
	BlobSha256 *string
}

func (q *Queries) ListTrash(ctx context.Context, arg ListTrashParams) ([]ListTrashRow, error) {
	rows, err := q.db.Query(ctx, listTrash, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashRow
	for rows.Next() {
		var i ListTrashRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashRootsForPurge = `-- name: ListTrashRootsForPurge :many
SELECT id FROM nodes n
WHERE n.owner_id = $1 AND n.deleted_at IS NOT NULL
  AND (n.parent_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM nodes p WHERE p.id = n.parent_id AND p.deleted_at IS NOT NULL))
`

func (q *Queries) ListTrashRootsForPurge(ctx context.Context, ownerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTrashRootsForPurge, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveNode = `-- name: MoveNode :one
UPDATE nodes SET parent_id = $3, updated_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
RETURNING id, owner_id, parent_id, name, kind, blob_id, deleted_at, created_at, updated_at
`

type MoveNodeParams struct {
	ID       uuid.UUID
	OwnerID  uuid.UUID
	ParentID *uuid.UUID
}

func (q *Queries) MoveNode(ctx context.Context, arg MoveNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, moveNode, arg.ID, arg.OwnerID, arg.ParentID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const purgeSubtree = `-- name: PurgeSubtree :many
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1 AND r.owner_id = $2
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
), deleted AS (
    DELETE FROM nodes WHERE nodes.id IN (SELECT s.id FROM sub s)
    RETURNING blob_id
)
SELECT d.blob_id FROM deleted d WHERE d.blob_id IS NOT NULL
`

type PurgeSubtreeParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

// 硬删子树,返回被删文件节点引用的 blob_id 供引用计数递减
func (q *Queries) PurgeSubtree(ctx context.Context, arg PurgeSubtreeParams) ([]*uuid.UUID, error) {
	rows, err := q.db.Query(ctx, purgeSubtree, arg.ID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*uuid.UUID
	for rows.Next() {
		var blob_id *uuid.UUID
		if err := rows.Scan(&blob_id); err != nil {
			return nil, err
		}
		items = append(items, blob_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameNode = `-- name: RenameNode :one
UPDATE nodes SET name = $3, updated_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
RETURNING id, owner_id, parent_id, name, kind, blob_id, deleted_at, created_at, updated_at
`

type RenameNodeParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Name    string
}

func (q *Queries) RenameNode(ctx context.Context, arg RenameNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, renameNode, arg.ID, arg.OwnerID, arg.Name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renameNodeAnyState = `-- name: RenameNodeAnyState :exec
UPDATE nodes SET name = $3, updated_at = now()
WHERE id = $1 AND owner_id = $2
`

type RenameNodeAnyStateParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Name    string
}

// 供回收站还原前解冲突用,不限制 deleted_at
func (q *Queries) RenameNodeAnyState(ctx context.Context, arg RenameNodeAnyStateParams) error {
	_, err := q.db.Exec(ctx, renameNodeAnyState, arg.ID, arg.OwnerID, arg.Name)
	return err
}

const restoreSubtree = `-- name: RestoreSubtree :exec
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1 AND r.owner_id = $2 AND r.deleted_at IS NOT NULL
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
    WHERE n.deleted_at IS NOT NULL
)
UPDATE nodes SET deleted_at = NULL
WHERE nodes.id IN (SELECT s.id FROM sub s)
`

type RestoreSubtreeParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) RestoreSubtree(ctx context.Context, arg RestoreSubtreeParams) error {
	_, err := q.db.Exec(ctx, restoreSubtree, arg.ID, arg.OwnerID)
	return err
}

const searchNodes = `-- name: SearchNodes :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1 AND n.deleted_at IS NULL AND n.name ILIKE '%' || $2 || '%'
ORDER BY n.updated_at DESC, n.id
LIMIT $3 OFFSET $4
`

type SearchNodesParams struct {
	OwnerID uuid.UUID
	Column2 *string
	Limit   int32
	Offset  int32
}

type SearchNodesRow struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	ParentID   *uuid.UUID
	Name       string
	Kind       string
	BlobID     *uuid.UUID
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	BlobSize   *int64
	BlobMime   *string
	BlobSha256 *string
}

func (q *Queries) SearchNodes(ctx context.Context, arg SearchNodesParams) ([]SearchNodesRow, error) {
	rows, err := q.db.Query(ctx, searchNodes,
		arg.OwnerID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNodesRow
	for rows.Next() {
		var i SearchNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const siblingNameExists = `-- name: SiblingNameExists :one
SELECT EXISTS (
    SELECT 1 FROM nodes
    WHERE owner_id = $1
      AND parent_id IS NOT DISTINCT FROM $2
      AND name = $3
      AND deleted_at IS NULL
) AS exists
`

type SiblingNameExistsParams struct {
	OwnerID  uuid.UUID
	ParentID *uuid.UUID
	Name     string
}

func (q *Queries) SiblingNameExists(ctx context.Context, arg SiblingNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, siblingNameExists, arg.OwnerID, arg.ParentID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteSubtree = `-- name: SoftDeleteSubtree :exec
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1 AND r.owner_id = $2 AND r.deleted_at IS NULL
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
    WHERE n.deleted_at IS NULL
)
UPDATE nodes SET deleted_at = now()
WHERE nodes.id IN (SELECT s.id FROM sub s)
`

type SoftDeleteSubtreeParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) SoftDeleteSubtree(ctx context.Context, arg SoftDeleteSubtreeParams) error {
	_, err := q.db.Exec(ctx, softDeleteSubtree, arg.ID, arg.OwnerID)
	return err
}

const subtractUsedBytes = `-- name: SubtractUsedBytes :exec
UPDATE users SET used_bytes = greatest(used_bytes - $2, 0) WHERE id = $1
`

type SubtractUsedBytesParams struct {
	ID        uuid.UUID
	UsedBytes int64
}

func (q *Queries) SubtractUsedBytes(ctx context.Context, arg SubtractUsedBytesParams) error {
	_, err := q.db.Exec(ctx, subtractUsedBytes, arg.ID, arg.UsedBytes)
	return err
}
