// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countChildren = `-- name: CountChildren :one
SELECT count(*) FROM nodes
WHERE owner_id = $1 AND parent_id IS NOT DISTINCT FROM $2 AND deleted_at IS NULL
`

type CountChildrenParams struct {
	OwnerID  uuid.UUID
	ParentID *uuid.UUID
}

func (q *Queries) CountChildren(ctx context.Context, arg CountChildrenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChildren, arg.OwnerID, arg.ParentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchNodes = `-- name: CountSearchNodes :one
SELECT count(*) FROM nodes
WHERE owner_id = $1 AND deleted_at IS NULL AND name ILIKE '%' || $2 || '%'
`

type CountSearchNodesParams struct {
	OwnerID uuid.UUID
	Column2 *string
}

func (q *Queries) CountSearchNodes(ctx context.Context, arg CountSearchNodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchNodes, arg.OwnerID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchNodesInSubtree = `-- name: CountSearchNodesInSubtree :one
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1 AND r.deleted_at IS NULL
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
    WHERE n.deleted_at IS NULL
)
SELECT count(*) FROM nodes n
WHERE n.id IN (SELECT s.id FROM sub s) AND n.name ILIKE '%' || $2 || '%'
`

type CountSearchNodesInSubtreeParams struct {
	ID      uuid.UUID
	Column2 *string
}

func (q *Queries) CountSearchNodesInSubtree(ctx context.Context, arg CountSearchNodesInSubtreeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchNodesInSubtree, arg.ID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrash = `-- name: CountTrash :one
SELECT count(*) FROM nodes n
WHERE n.owner_id = $1 AND n.deleted_at IS NOT NULL
  AND (n.parent_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM nodes p WHERE p.id = n.parent_id AND p.deleted_at IS NOT NULL))
`

func (q *Queries) CountTrash(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTrash, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (id, owner_id, parent_id, name, kind, blob_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, parent_id, name, kind, blob_id, deleted_at, created_at, updated_at, subtree_bytes, subtree_count, stats_stale
`

type CreateNodeParams struct {
	ID       uuid.UUID
	OwnerID  uuid.UUID
	ParentID *uuid.UUID
	Name     string
	Kind     string
	BlobID   *uuid.UUID
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ID,
		arg.OwnerID,
		arg.ParentID,
		arg.Name,
		arg.Kind,
		arg.BlobID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubtreeBytes,
		&i.SubtreeCount,
		&i.StatsStale,
	)
	return i, err
}

const decrementBlobRefs = `-- name: DecrementBlobRefs :exec
UPDATE blobs SET
    ref_count = ref_count - 1,
    deref_at  = CASE WHEN ref_count - 1 = 0 THEN now() ELSE deref_at END
WHERE id = ANY($1::uuid[])
`

func (q *Queries) DecrementBlobRefs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementBlobRefs, dollar_1)
	return err
}

const getActiveNodeOwned = `-- name: GetActiveNodeOwned :one
SELECT id, owner_id, parent_id, name, kind, blob_id, deleted_at, created_at, updated_at, subtree_bytes, subtree_count, stats_stale FROM nodes WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type GetActiveNodeOwnedParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetActiveNodeOwned(ctx context.Context, arg GetActiveNodeOwnedParams) (Node, error) {
	row := q.db.QueryRow(ctx, getActiveNodeOwned, arg.ID, arg.OwnerID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubtreeBytes,
		&i.SubtreeCount,
		&i.StatsStale,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, owner_id, parent_id, name, kind, blob_id, deleted_at, created_at, updated_at, subtree_bytes, subtree_count, stats_stale FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubtreeBytes,
		&i.SubtreeCount,
		&i.StatsStale,
	)
	return i, err
}

const getNodeWithBlob = `-- name: GetNodeWithBlob :one
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256, b.verified AS blob_verified
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.id = $1 AND n.owner_id = $2
`

type GetNodeWithBlobParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

type GetNodeWithBlobRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
	BlobVerified *bool
}

func (q *Queries) GetNodeWithBlob(ctx context.Context, arg GetNodeWithBlobParams) (GetNodeWithBlobRow, error) {
	row := q.db.QueryRow(ctx, getNodeWithBlob, arg.ID, arg.OwnerID)
	var i GetNodeWithBlobRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubtreeBytes,
		&i.SubtreeCount,
		&i.StatsStale,
		&i.BlobSize,
		&i.BlobMime,
		&i.BlobSha256,
		&i.BlobVerified,
	)
	return i, err
}

const isDescendant = `-- name: IsDescendant :one
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
)
SELECT count(*) > 0 AS is_descendant
FROM nodes x
WHERE x.id = $2 AND x.id IN (SELECT s.id FROM sub s)
`

type IsDescendantParams struct {
	ID   uuid.UUID
	ID_2 uuid.UUID
}

// $2(candidate)是否在 $1(ancestor)的子树内(含自身)
func (q *Queries) IsDescendant(ctx context.Context, arg IsDescendantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDescendant, arg.ID, arg.ID_2)
	var is_descendant bool
	err := row.Scan(&is_descendant)
	return is_descendant, err
}

const listActiveChildrenLite = `-- name: ListActiveChildrenLite :many
SELECT n.id, n.name, n.kind, n.blob_id, b.sha256 AS blob_sha256, b.size AS blob_size
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.parent_id = $1 AND n.deleted_at IS NULL
ORDER BY n.kind DESC, n.name
`

type ListActiveChildrenLiteRow struct {
	ID         uuid.UUID
	Name       string
	Kind       string
	BlobID     *uuid.UUID
	BlobSha256 *string
	BlobSize   *int64
}

// 打包下载 / 复制的树遍历用,不分页
func (q *Queries) ListActiveChildrenLite(ctx context.Context, parentID *uuid.UUID) ([]ListActiveChildrenLiteRow, error) {
	rows, err := q.db.Query(ctx, listActiveChildrenLite, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveChildrenLiteRow
	for rows.Next() {
		var i ListActiveChildrenLiteRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.BlobSha256,
			&i.BlobSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildren = `-- name: ListChildren :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1
  AND n.parent_id IS NOT DISTINCT FROM $2
  AND n.deleted_at IS NULL
ORDER BY
  n.kind DESC, -- folder 在前
  CASE WHEN $3::text = 'NAME'       AND NOT $4::boolean THEN n.name END ASC,
  CASE WHEN $3::text = 'NAME'       AND     $4::boolean THEN n.name END DESC,
  CASE WHEN $3::text = 'SIZE'       AND NOT $4::boolean THEN b.size END ASC NULLS FIRST,
  CASE WHEN $3::text = 'SIZE'       AND     $4::boolean THEN b.size END DESC NULLS LAST,
  CASE WHEN $3::text = 'UPDATED_AT' AND NOT $4::boolean THEN n.updated_at END ASC,
  CASE WHEN $3::text = 'UPDATED_AT' AND     $4::boolean THEN n.updated_at END DESC,
  n.id
LIMIT $5
`

type ListChildrenParams struct {
	OwnerID    uuid.UUID
	ParentID   *uuid.UUID
	OrderBy    string
	Descending bool
	PageLimit  int32
}

type ListChildrenRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

// 首页(无 cursor)。翻页走下面 6 条 keyset 查询,方向拆开写,不用 CASE 包 WHERE,留住索引通道。
func (q *Queries) ListChildren(ctx context.Context, arg ListChildrenParams) ([]ListChildrenRow, error) {
	rows, err := q.db.Query(ctx, listChildren,
		arg.OwnerID,
		arg.ParentID,
		arg.OrderBy,
		arg.Descending,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenRow
	for rows.Next() {
		var i ListChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenNameAsc = `-- name: ListChildrenNameAsc :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1
  AND n.parent_id IS NOT DISTINCT FROM $2
  AND n.deleted_at IS NULL
  AND (n.kind < $3::text
       OR (n.kind = $3::text
           AND (n.name > $4::text
                OR (n.name = $4::text AND n.id > $5))))
ORDER BY n.kind DESC, n.name ASC, n.id
LIMIT $6
`

type ListChildrenNameAscParams struct {
	OwnerID   uuid.UUID
	ParentID  *uuid.UUID
	CKind     string
	CName     string
	CID       uuid.UUID
	PageLimit int32
}

type ListChildrenNameAscRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

func (q *Queries) ListChildrenNameAsc(ctx context.Context, arg ListChildrenNameAscParams) ([]ListChildrenNameAscRow, error) {
	rows, err := q.db.Query(ctx, listChildrenNameAsc,
		arg.OwnerID,
		arg.ParentID,
		arg.CKind,
		arg.CName,
		arg.CID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenNameAscRow
	for rows.Next() {
		var i ListChildrenNameAscRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenNameDesc = `-- name: ListChildrenNameDesc :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1
  AND n.parent_id IS NOT DISTINCT FROM $2
  AND n.deleted_at IS NULL
  AND (n.kind < $3::text
       OR (n.kind = $3::text
           AND (n.name < $4::text
                OR (n.name = $4::text AND n.id > $5))))
ORDER BY n.kind DESC, n.name DESC, n.id
LIMIT $6
`

type ListChildrenNameDescParams struct {
	OwnerID   uuid.UUID
	ParentID  *uuid.UUID
	CKind     string
	CName     string
	CID       uuid.UUID
	PageLimit int32
}

type ListChildrenNameDescRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

func (q *Queries) ListChildrenNameDesc(ctx context.Context, arg ListChildrenNameDescParams) ([]ListChildrenNameDescRow, error) {
	rows, err := q.db.Query(ctx, listChildrenNameDesc,
		arg.OwnerID,
		arg.ParentID,
		arg.CKind,
		arg.CName,
		arg.CID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenNameDescRow
	for rows.Next() {
		var i ListChildrenNameDescRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenSizeAsc = `-- name: ListChildrenSizeAsc :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1
  AND n.parent_id IS NOT DISTINCT FROM $2
  AND n.deleted_at IS NULL
  AND (n.kind < $3::text
       OR (n.kind = $3::text
           AND (($4::boolean AND ((b.size IS NULL AND n.id > $5) OR b.size IS NOT NULL))
                OR (NOT $4::boolean
                    AND (b.size > $6::bigint
                         OR (b.size = $6::bigint AND n.id > $5))))))
ORDER BY n.kind DESC, b.size ASC NULLS FIRST, n.id
LIMIT $7
`

type ListChildrenSizeAscParams struct {
	OwnerID   uuid.UUID
	ParentID  *uuid.UUID
	CKind     string
	CSizeNull bool
	CID       uuid.UUID
	CSize     int64
	PageLimit int32
}

type ListChildrenSizeAscRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

// SIZE 键可空(文件夹无 blob):ASC NULLS FIRST——cursor 键为空时,"之后" = 同为空且 id 更大,或键非空
func (q *Queries) ListChildrenSizeAsc(ctx context.Context, arg ListChildrenSizeAscParams) ([]ListChildrenSizeAscRow, error) {
	rows, err := q.db.Query(ctx, listChildrenSizeAsc,
		arg.OwnerID,
		arg.ParentID,
		arg.CKind,
		arg.CSizeNull,
		arg.CID,
		arg.CSize,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenSizeAscRow
	for rows.Next() {
		var i ListChildrenSizeAscRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenSizeDesc = `-- name: ListChildrenSizeDesc :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1
  AND n.parent_id IS NOT DISTINCT FROM $2
  AND n.deleted_at IS NULL
  AND (n.kind < $3::text
       OR (n.kind = $3::text
           AND (($4::boolean AND b.size IS NULL AND n.id > $5)
                OR (NOT $4::boolean
                    AND (b.size < $6::bigint
                         OR (b.size = $6::bigint AND n.id > $5)
                         OR b.size IS NULL)))))
ORDER BY n.kind DESC, b.size DESC NULLS LAST, n.id
LIMIT $7
`

type ListChildrenSizeDescParams struct {
	OwnerID   uuid.UUID
	ParentID  *uuid.UUID
	CKind     string
	CSizeNull bool
	CID       uuid.UUID
	CSize     int64
	PageLimit int32
}

type ListChildrenSizeDescRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

// DESC NULLS LAST——cursor 键非空时,"之后" = 键更小,或同键 id 更大,或键为空
func (q *Queries) ListChildrenSizeDesc(ctx context.Context, arg ListChildrenSizeDescParams) ([]ListChildrenSizeDescRow, error) {
	rows, err := q.db.Query(ctx, listChildrenSizeDesc,
		arg.OwnerID,
		arg.ParentID,
		arg.CKind,
		arg.CSizeNull,
		arg.CID,
		arg.CSize,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenSizeDescRow
	for rows.Next() {
		var i ListChildrenSizeDescRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenUpdatedAsc = `-- name: ListChildrenUpdatedAsc :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1
  AND n.parent_id IS NOT DISTINCT FROM $2
  AND n.deleted_at IS NULL
  AND (n.kind < $3::text
       OR (n.kind = $3::text
           AND (n.updated_at > $4::timestamptz
                OR (n.updated_at = $4::timestamptz AND n.id > $5))))
ORDER BY n.kind DESC, n.updated_at ASC, n.id
LIMIT $6
`

type ListChildrenUpdatedAscParams struct {
	OwnerID   uuid.UUID
	ParentID  *uuid.UUID
	CKind     string
	CUpdated  pgtype.Timestamptz
	CID       uuid.UUID
	PageLimit int32
}

type ListChildrenUpdatedAscRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

func (q *Queries) ListChildrenUpdatedAsc(ctx context.Context, arg ListChildrenUpdatedAscParams) ([]ListChildrenUpdatedAscRow, error) {
	rows, err := q.db.Query(ctx, listChildrenUpdatedAsc,
		arg.OwnerID,
		arg.ParentID,
		arg.CKind,
		arg.CUpdated,
		arg.CID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenUpdatedAscRow
	for rows.Next() {
		var i ListChildrenUpdatedAscRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenUpdatedDesc = `-- name: ListChildrenUpdatedDesc :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1
  AND n.parent_id IS NOT DISTINCT FROM $2
  AND n.deleted_at IS NULL
  AND (n.kind < $3::text
       OR (n.kind = $3::text
           AND (n.updated_at < $4::timestamptz
                OR (n.updated_at = $4::timestamptz AND n.id > $5))))
ORDER BY n.kind DESC, n.updated_at DESC, n.id
LIMIT $6
`

type ListChildrenUpdatedDescParams struct {
	OwnerID   uuid.UUID
	ParentID  *uuid.UUID
	CKind     string
	CUpdated  pgtype.Timestamptz
	CID       uuid.UUID
	PageLimit int32
}

type ListChildrenUpdatedDescRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

func (q *Queries) ListChildrenUpdatedDesc(ctx context.Context, arg ListChildrenUpdatedDescParams) ([]ListChildrenUpdatedDescRow, error) {
	rows, err := q.db.Query(ctx, listChildrenUpdatedDesc,
		arg.OwnerID,
		arg.ParentID,
		arg.CKind,
		arg.CUpdated,
		arg.CID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenUpdatedDescRow
	for rows.Next() {
		var i ListChildrenUpdatedDescRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredTrashRoots = `-- name: ListExpiredTrashRoots :many
SELECT n.id, n.owner_id FROM nodes n
WHERE n.deleted_at IS NOT NULL AND n.deleted_at < $1
  AND (n.parent_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM nodes p WHERE p.id = n.parent_id AND p.deleted_at IS NOT NULL))
LIMIT 500
`

type ListExpiredTrashRootsRow struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

// 全用户的过期回收站顶层(整树软删是同一时刻,只看顶层即可)
func (q *Queries) ListExpiredTrashRoots(ctx context.Context, deletedAt pgtype.Timestamptz) ([]ListExpiredTrashRootsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredTrashRoots, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredTrashRootsRow
	for rows.Next() {
		var i ListExpiredTrashRootsRow
		if err := rows.Scan(&i.ID, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleFolders = `-- name: ListStaleFolders :many
SELECT id FROM nodes
WHERE kind = 'folder' AND stats_stale AND deleted_at IS NULL
LIMIT $1
`

func (q *Queries) ListStaleFolders(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStaleFolders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrash = `-- name: ListTrash :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1 AND n.deleted_at IS NOT NULL
  -- 只列回收站顶层:父不存在、父未删,或父先于自己被单独删除后还原过
  AND (n.parent_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM nodes p WHERE p.id = n.parent_id AND p.deleted_at IS NOT NULL))
ORDER BY n.deleted_at DESC, n.id
LIMIT $2
`

type ListTrashParams struct {
	OwnerID uuid.UUID
	Limit   int32
}

type ListTrashRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

func (q *Queries) ListTrash(ctx context.Context, arg ListTrashParams) ([]ListTrashRow, error) {
	rows, err := q.db.Query(ctx, listTrash, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashRow
	for rows.Next() {
		var i ListTrashRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashAfter = `-- name: ListTrashAfter :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1 AND n.deleted_at IS NOT NULL
  AND (n.parent_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM nodes p WHERE p.id = n.parent_id AND p.deleted_at IS NOT NULL))
  AND (n.deleted_at < $3::timestamptz
       OR (n.deleted_at = $3::timestamptz AND n.id > $4))
ORDER BY n.deleted_at DESC, n.id
LIMIT $2
`

type ListTrashAfterParams struct {
	OwnerID  uuid.UUID
	Limit    int32
	CDeleted pgtype.Timestamptz
	CID      uuid.UUID
}

type ListTrashAfterRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

func (q *Queries) ListTrashAfter(ctx context.Context, arg ListTrashAfterParams) ([]ListTrashAfterRow, error) {
	rows, err := q.db.Query(ctx, listTrashAfter,
		arg.OwnerID,
		arg.Limit,
		arg.CDeleted,
		arg.CID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashAfterRow
	for rows.Next() {
		var i ListTrashAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashRootsForPurge = `-- name: ListTrashRootsForPurge :many
SELECT id FROM nodes n
WHERE n.owner_id = $1 AND n.deleted_at IS NOT NULL
  AND (n.parent_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM nodes p WHERE p.id = n.parent_id AND p.deleted_at IS NOT NULL))
`

func (q *Queries) ListTrashRootsForPurge(ctx context.Context, ownerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTrashRootsForPurge, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAncestorsStale = `-- name: MarkAncestorsStale :exec

WITH RECURSIVE anc AS (
    SELECT n.id, n.parent_id FROM nodes n WHERE n.id = $1
    UNION ALL
    SELECT p.id, p.parent_id FROM nodes p JOIN anc a ON p.id = a.parent_id
)
UPDATE nodes SET stats_stale = true
WHERE nodes.id IN (SELECT a.id FROM anc a) AND nodes.kind = 'folder'
`

// ---- 子树统计(异步,最终一致) ----
// 从 $1(含自身)沿父链向上,把途经的 folder 全部标脏
func (q *Queries) MarkAncestorsStale(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAncestorsStale, id)
	return err
}

const moveNode = `-- name: MoveNode :one
UPDATE nodes SET parent_id = $3, updated_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
RETURNING id, owner_id, parent_id, name, kind, blob_id, deleted_at, created_at, updated_at, subtree_bytes, subtree_count, stats_stale
`

type MoveNodeParams struct {
	ID       uuid.UUID
	OwnerID  uuid.UUID
	ParentID *uuid.UUID
}

func (q *Queries) MoveNode(ctx context.Context, arg MoveNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, moveNode, arg.ID, arg.OwnerID, arg.ParentID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubtreeBytes,
		&i.SubtreeCount,
		&i.StatsStale,
	)
	return i, err
}

const purgeSubtree = `-- name: PurgeSubtree :many
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1 AND r.owner_id = $2
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
), deleted AS (
    DELETE FROM nodes WHERE nodes.id IN (SELECT s.id FROM sub s)
    RETURNING blob_id
)
SELECT d.blob_id FROM deleted d WHERE d.blob_id IS NOT NULL
`

type PurgeSubtreeParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

// 硬删子树,返回被删文件节点引用的 blob_id 供引用计数递减
func (q *Queries) PurgeSubtree(ctx context.Context, arg PurgeSubtreeParams) ([]*uuid.UUID, error) {
	rows, err := q.db.Query(ctx, purgeSubtree, arg.ID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*uuid.UUID
	for rows.Next() {
		var blob_id *uuid.UUID
		if err := rows.Scan(&blob_id); err != nil {
			return nil, err
		}
		items = append(items, blob_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeFolderStats = `-- name: RecomputeFolderStats :exec
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1 AND r.deleted_at IS NULL
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
    WHERE n.deleted_at IS NULL
), agg AS (
    SELECT COALESCE(sum(b.size), 0)::bigint AS bytes, count(b.id) AS files
    FROM nodes f
    LEFT JOIN blobs b ON b.id = f.blob_id
    WHERE f.id IN (SELECT s.id FROM sub s) AND f.kind = 'file'
)
UPDATE nodes SET
    subtree_bytes = agg.bytes,
    subtree_count = agg.files,
    stats_stale   = false
FROM agg
WHERE nodes.id = $1
`

// 单语句重算:行锁保证与并发标脏串行化;重算窗口内的新变更会再次置脏,下一轮修正
func (q *Queries) RecomputeFolderStats(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recomputeFolderStats, id)
	return err
}

const renameNode = `-- name: RenameNode :one
UPDATE nodes SET name = $3, updated_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
RETURNING id, owner_id, parent_id, name, kind, blob_id, deleted_at, created_at, updated_at, subtree_bytes, subtree_count, stats_stale
`

type RenameNodeParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Name    string
}

func (q *Queries) RenameNode(ctx context.Context, arg RenameNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, renameNode, arg.ID, arg.OwnerID, arg.Name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.BlobID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubtreeBytes,
		&i.SubtreeCount,
		&i.StatsStale,
	)
	return i, err
}

const renameNodeAnyState = `-- name: RenameNodeAnyState :exec
UPDATE nodes SET name = $3, updated_at = now()
WHERE id = $1 AND owner_id = $2
`

type RenameNodeAnyStateParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Name    string
}

// 供回收站还原前解冲突用,不限制 deleted_at
func (q *Queries) RenameNodeAnyState(ctx context.Context, arg RenameNodeAnyStateParams) error {
	_, err := q.db.Exec(ctx, renameNodeAnyState, arg.ID, arg.OwnerID, arg.Name)
	return err
}

const restoreSubtree = `-- name: RestoreSubtree :exec
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1 AND r.owner_id = $2 AND r.deleted_at IS NOT NULL
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
    WHERE n.deleted_at IS NOT NULL
)
UPDATE nodes SET deleted_at = NULL
WHERE nodes.id IN (SELECT s.id FROM sub s)
`

type RestoreSubtreeParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) RestoreSubtree(ctx context.Context, arg RestoreSubtreeParams) error {
	_, err := q.db.Exec(ctx, restoreSubtree, arg.ID, arg.OwnerID)
	return err
}

const searchNodes = `-- name: SearchNodes :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1 AND n.deleted_at IS NULL AND n.name ILIKE '%' || $2 || '%'
ORDER BY n.updated_at DESC, n.id
LIMIT $3
`

type SearchNodesParams struct {
	OwnerID uuid.UUID
	Column2 *string
	Limit   int32
}

type SearchNodesRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

func (q *Queries) SearchNodes(ctx context.Context, arg SearchNodesParams) ([]SearchNodesRow, error) {
	rows, err := q.db.Query(ctx, searchNodes, arg.OwnerID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNodesRow
	for rows.Next() {
		var i SearchNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNodesAfter = `-- name: SearchNodesAfter :many
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.owner_id = $1 AND n.deleted_at IS NULL AND n.name ILIKE '%' || $2 || '%'
  AND (n.updated_at < $4::timestamptz
       OR (n.updated_at = $4::timestamptz AND n.id > $5))
ORDER BY n.updated_at DESC, n.id
LIMIT $3
`

type SearchNodesAfterParams struct {
	OwnerID  uuid.UUID
	Column2  *string
	Limit    int32
	CUpdated pgtype.Timestamptz
	CID      uuid.UUID
}

type SearchNodesAfterRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

func (q *Queries) SearchNodesAfter(ctx context.Context, arg SearchNodesAfterParams) ([]SearchNodesAfterRow, error) {
	rows, err := q.db.Query(ctx, searchNodesAfter,
		arg.OwnerID,
		arg.Column2,
		arg.Limit,
		arg.CUpdated,
		arg.CID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNodesAfterRow
	for rows.Next() {
		var i SearchNodesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNodesInSubtree = `-- name: SearchNodesInSubtree :many
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1 AND r.deleted_at IS NULL
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
    WHERE n.deleted_at IS NULL
)
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.id IN (SELECT s.id FROM sub s) AND n.name ILIKE '%' || $2 || '%'
ORDER BY n.updated_at DESC, n.id
LIMIT $3
`

type SearchNodesInSubtreeParams struct {
	ID      uuid.UUID
	Column2 *string
	Limit   int32
}

type SearchNodesInSubtreeRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

// 访客搜索:范围限定在分享根($1)的子树内
func (q *Queries) SearchNodesInSubtree(ctx context.Context, arg SearchNodesInSubtreeParams) ([]SearchNodesInSubtreeRow, error) {
	rows, err := q.db.Query(ctx, searchNodesInSubtree, arg.ID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNodesInSubtreeRow
	for rows.Next() {
		var i SearchNodesInSubtreeRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNodesInSubtreeAfter = `-- name: SearchNodesInSubtreeAfter :many
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1 AND r.deleted_at IS NULL
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
    WHERE n.deleted_at IS NULL
)
SELECT n.id, n.owner_id, n.parent_id, n.name, n.kind, n.blob_id, n.deleted_at, n.created_at, n.updated_at, n.subtree_bytes, n.subtree_count, n.stats_stale, b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM nodes n
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE n.id IN (SELECT s.id FROM sub s) AND n.name ILIKE '%' || $2 || '%'
  AND (n.updated_at < $4::timestamptz
       OR (n.updated_at = $4::timestamptz AND n.id > $5))
ORDER BY n.updated_at DESC, n.id
LIMIT $3
`

type SearchNodesInSubtreeAfterParams struct {
	ID       uuid.UUID
	Column2  *string
	Limit    int32
	CUpdated pgtype.Timestamptz
	CID      uuid.UUID
}

type SearchNodesInSubtreeAfterRow struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Kind         string
	BlobID       *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubtreeBytes int64
	SubtreeCount int64
	StatsStale   bool
	BlobSize     *int64
	BlobMime     *string
	BlobSha256   *string
}

func (q *Queries) SearchNodesInSubtreeAfter(ctx context.Context, arg SearchNodesInSubtreeAfterParams) ([]SearchNodesInSubtreeAfterRow, error) {
	rows, err := q.db.Query(ctx, searchNodesInSubtreeAfter,
		arg.ID,
		arg.Column2,
		arg.Limit,
		arg.CUpdated,
		arg.CID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNodesInSubtreeAfterRow
	for rows.Next() {
		var i SearchNodesInSubtreeAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.BlobID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtreeBytes,
			&i.SubtreeCount,
			&i.StatsStale,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const siblingNameExists = `-- name: SiblingNameExists :one
SELECT EXISTS (
    SELECT 1 FROM nodes
    WHERE owner_id = $1
      AND parent_id IS NOT DISTINCT FROM $2
      AND name = $3
      AND deleted_at IS NULL
) AS exists
`

type SiblingNameExistsParams struct {
	OwnerID  uuid.UUID
	ParentID *uuid.UUID
	Name     string
}

func (q *Queries) SiblingNameExists(ctx context.Context, arg SiblingNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, siblingNameExists, arg.OwnerID, arg.ParentID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteSubtree = `-- name: SoftDeleteSubtree :exec
WITH RECURSIVE sub AS (
    SELECT r.id FROM nodes r WHERE r.id = $1 AND r.owner_id = $2 AND r.deleted_at IS NULL
    UNION ALL
    SELECT n.id FROM nodes n JOIN sub s ON n.parent_id = s.id
    WHERE n.deleted_at IS NULL
)
UPDATE nodes SET deleted_at = now()
WHERE nodes.id IN (SELECT s.id FROM sub s)
`

type SoftDeleteSubtreeParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) SoftDeleteSubtree(ctx context.Context, arg SoftDeleteSubtreeParams) error {
	_, err := q.db.Exec(ctx, softDeleteSubtree, arg.ID, arg.OwnerID)
	return err
}

const subtractUsedBytes = `-- name: SubtractUsedBytes :exec
UPDATE users SET used_bytes = greatest(used_bytes - $2, 0) WHERE id = $1
`

type SubtractUsedBytesParams struct {
	ID        uuid.UUID
	UsedBytes int64
}

func (q *Queries) SubtractUsedBytes(ctx context.Context, arg SubtractUsedBytesParams) error {
	_, err := q.db.Exec(ctx, subtractUsedBytes, arg.ID, arg.UsedBytes)
	return err
}
