// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOAuthAuthorizationCode = `-- name: ConsumeOAuthAuthorizationCode :one
DELETE FROM oauth_authorization_codes
WHERE code_hash = $1 AND expires_at > now()
RETURNING code_hash, grant_id, client_id, redirect_uri, scopes, code_challenge, expires_at, created_at
`

func (q *Queries) ConsumeOAuthAuthorizationCode(ctx context.Context, codeHash string) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, consumeOAuthAuthorizationCode, codeHash)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.CodeHash,
		&i.GrantID,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.CodeChallenge,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeOAuthRefreshToken = `-- name: ConsumeOAuthRefreshToken :one
UPDATE oauth_refresh_tokens SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND revoked_at IS NULL AND expires_at > now()
RETURNING id, grant_id, token_hash, scopes, expires_at, used_at, revoked_at, created_at
`

func (q *Queries) ConsumeOAuthRefreshToken(ctx context.Context, tokenHash string) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeOAuthRefreshToken, tokenHash)
	var i OauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthAccessToken = `-- name: CreateOAuthAccessToken :one
INSERT INTO oauth_access_tokens (id, grant_id, token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, grant_id, token_hash, scopes, expires_at, created_at, last_used_at
`

type CreateOAuthAccessTokenParams struct {
	ID        uuid.UUID
	GrantID   uuid.UUID
	TokenHash string
	Scopes    []string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateOAuthAccessToken(ctx context.Context, arg CreateOAuthAccessTokenParams) (OauthAccessToken, error) {
	row := q.db.QueryRow(ctx, createOAuthAccessToken,
		arg.ID,
		arg.GrantID,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i OauthAccessToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createOAuthAuthorizationCode = `-- name: CreateOAuthAuthorizationCode :exec
INSERT INTO oauth_authorization_codes
    (code_hash, grant_id, client_id, redirect_uri, scopes, code_challenge, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOAuthAuthorizationCodeParams struct {
	CodeHash      string
	GrantID       uuid.UUID
	ClientID      string
	RedirectUri   string
	Scopes        []string
	CodeChallenge string
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateOAuthAuthorizationCode(ctx context.Context, arg CreateOAuthAuthorizationCodeParams) error {
	_, err := q.db.Exec(ctx, createOAuthAuthorizationCode,
		arg.CodeHash,
		arg.GrantID,
		arg.ClientID,
		arg.RedirectUri,
		arg.Scopes,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (client_id, client_name, redirect_uris)
VALUES ($1, $2, $3)
RETURNING client_id, client_name, redirect_uris, created_at
`

type CreateOAuthClientParams struct {
	ClientID     string
	ClientName   string
	RedirectUris []string
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient, arg.ClientID, arg.ClientName, arg.RedirectUris)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthRefreshToken = `-- name: CreateOAuthRefreshToken :one
INSERT INTO oauth_refresh_tokens (id, grant_id, token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, grant_id, token_hash, scopes, expires_at, used_at, revoked_at, created_at
`

type CreateOAuthRefreshTokenParams struct {
	ID        uuid.UUID
	GrantID   uuid.UUID
	TokenHash string
	Scopes    []string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateOAuthRefreshToken(ctx context.Context, arg CreateOAuthRefreshTokenParams) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, createOAuthRefreshToken,
		arg.ID,
		arg.GrantID,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i OauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAccessTokenByHash = `-- name: GetOAuthAccessTokenByHash :one
SELECT oat.id, oat.grant_id, oat.token_hash, oat.scopes, oat.expires_at, oat.created_at, oat.last_used_at, og.user_id, og.scopes AS grant_scopes, og.revoked_at AS grant_revoked_at,
       oc.client_name, u.username,
       (u.disabled_at IS NOT NULL)::boolean AS owner_disabled
FROM oauth_access_tokens oat
JOIN oauth_grants og ON og.id = oat.grant_id
JOIN oauth_clients oc ON oc.client_id = og.client_id
JOIN users u ON u.id = og.user_id
WHERE oat.token_hash = $1 AND oat.expires_at > now()
`

type GetOAuthAccessTokenByHashRow struct {
	ID             uuid.UUID
	GrantID        uuid.UUID
	TokenHash      string
	Scopes         []string
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
	UserID         uuid.UUID
	GrantScopes    []string
	GrantRevokedAt pgtype.Timestamptz
	ClientName     string
	Username       string
	OwnerDisabled  bool
}

func (q *Queries) GetOAuthAccessTokenByHash(ctx context.Context, tokenHash string) (GetOAuthAccessTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAccessTokenByHash, tokenHash)
	var i GetOAuthAccessTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.UserID,
		&i.GrantScopes,
		&i.GrantRevokedAt,
		&i.ClientName,
		&i.Username,
		&i.OwnerDisabled,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT client_id, client_name, redirect_uris, created_at FROM oauth_clients WHERE client_id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthGrant = `-- name: GetOAuthGrant :one
SELECT og.id, og.user_id, og.client_id, og.scopes, og.created_at, og.updated_at, og.revoked_at, oc.client_name, oc.redirect_uris,
       (u.disabled_at IS NOT NULL)::boolean AS owner_disabled
FROM oauth_grants og
JOIN oauth_clients oc ON oc.client_id = og.client_id
JOIN users u ON u.id = og.user_id
WHERE og.id = $1
`

type GetOAuthGrantRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ClientID      string
	Scopes        []string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	ClientName    string
	RedirectUris  []string
	OwnerDisabled bool
}

func (q *Queries) GetOAuthGrant(ctx context.Context, id uuid.UUID) (GetOAuthGrantRow, error) {
	row := q.db.QueryRow(ctx, getOAuthGrant, id)
	var i GetOAuthGrantRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.ClientName,
		&i.RedirectUris,
		&i.OwnerDisabled,
	)
	return i, err
}

const listOAuthGrants = `-- name: ListOAuthGrants :many
SELECT og.id, og.client_id, oc.client_name, og.scopes, og.created_at, og.updated_at
FROM oauth_grants og
JOIN oauth_clients oc ON oc.client_id = og.client_id
WHERE og.user_id = $1 AND og.revoked_at IS NULL
ORDER BY og.updated_at DESC
`

type ListOAuthGrantsRow struct {
	ID         uuid.UUID
	ClientID   string
	ClientName string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListOAuthGrants(ctx context.Context, userID uuid.UUID) ([]ListOAuthGrantsRow, error) {
	rows, err := q.db.Query(ctx, listOAuthGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOAuthGrantsRow
	for rows.Next() {
		var i ListOAuthGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOAuthGrant = `-- name: RevokeOAuthGrant :execrows
UPDATE oauth_grants SET revoked_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeOAuthGrantParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeOAuthGrant(ctx context.Context, arg RevokeOAuthGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOAuthGrant, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchOAuthAccessToken = `-- name: TouchOAuthAccessToken :exec
UPDATE oauth_access_tokens SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

func (q *Queries) TouchOAuthAccessToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchOAuthAccessToken, id)
	return err
}

const upsertOAuthGrant = `-- name: UpsertOAuthGrant :one
INSERT INTO oauth_grants (id, user_id, client_id, scopes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, client_id) DO UPDATE
SET scopes = EXCLUDED.scopes, updated_at = now(), revoked_at = NULL
RETURNING id, user_id, client_id, scopes, created_at, updated_at, revoked_at
`

type UpsertOAuthGrantParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	ClientID string
	Scopes   []string
}

func (q *Queries) UpsertOAuthGrant(ctx context.Context, arg UpsertOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, upsertOAuthGrant,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
	)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}
