// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (family_id, user_id, user_agent, ip)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	FamilyID  uuid.UUID
	UserID    uuid.UUID
	UserAgent string
	Ip        string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.FamilyID,
		arg.UserID,
		arg.UserAgent,
		arg.Ip,
	)
	return err
}

const deleteStaleSessions = `-- name: DeleteStaleSessions :execrows
DELETE FROM sessions WHERE last_seen_at < now() - interval '90 days'
`

// 90 天没活动的记录清掉。会话列表只对近期有意义,不需要永久留痕。
func (q *Queries) DeleteStaleSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSessions = `-- name: ListSessions :many
SELECT s.family_id, s.user_agent, s.ip, s.created_at, s.last_seen_at, s.revoked_at,
       EXISTS (
           SELECT 1 FROM refresh_tokens r
           WHERE r.family_id = s.family_id
             AND r.revoked_at IS NULL
             AND r.expires_at > now()
       ) AS active
FROM sessions s
WHERE s.user_id = $1
ORDER BY s.last_seen_at DESC
LIMIT 50
`

type ListSessionsRow struct {
	FamilyID   uuid.UUID
	UserAgent  string
	Ip         string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	Active     bool
}

// active 表示这族 refresh token 还能用(没被吊销、没过期)。被挤下线的会话
// (改密、管理员禁用、重放检测)会以 active=false 的形式留在列表里,让用户看得见
// "某个设备刚刚被强制下线"——这正是重放检测唯一能被用户感知的地方。
func (q *Queries) ListSessions(ctx context.Context, userID uuid.UUID) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.FamilyID,
			&i.UserAgent,
			&i.Ip,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = now()
WHERE family_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	FamilyID uuid.UUID
	UserID   uuid.UUID
}

// 必须与 RevokeRefreshFamily 成对调用,否则只是标记了展示状态、token 仍能用。
func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now()
WHERE family_id = $1
  AND last_seen_at < now() - interval '5 minutes'
`

// 5 分钟才写一次(照 TouchAppPassword 的做法)。活跃会话不该把每次请求都变成一次写。
func (q *Queries) TouchSession(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, familyID)
	return err
}
