// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShare = `-- name: CreateShare :one
INSERT INTO shares (id, token, node_id, created_by, password_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, token, node_id, created_by, password_hash, expires_at, revoked_at, created_at
`

type CreateShareParams struct {
	ID           uuid.UUID
	Token        string
	NodeID       uuid.UUID
	CreatedBy    uuid.UUID
	PasswordHash *string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (Share, error) {
	row := q.db.QueryRow(ctx, createShare,
		arg.ID,
		arg.Token,
		arg.NodeID,
		arg.CreatedBy,
		arg.PasswordHash,
		arg.ExpiresAt,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.NodeID,
		&i.CreatedBy,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredShareVisits = `-- name: DeleteExpiredShareVisits :execrows
DELETE FROM share_visits WHERE created_at < now() - interval '180 days'
`

// 保留 180 天。所以对外说的"访问次数"是近 180 天的语义,别当成历史总量。
func (q *Queries) DeleteExpiredShareVisits(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredShareVisits)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getShareByID = `-- name: GetShareByID :one
SELECT s.id, s.token, s.node_id, s.created_by, s.password_hash, s.expires_at, s.revoked_at, s.created_at, n.name AS node_name, n.kind AS node_kind, n.deleted_at AS node_deleted_at,
       (u.disabled_at IS NOT NULL)::boolean AS owner_disabled
FROM shares s JOIN nodes n ON n.id = s.node_id JOIN users u ON u.id = s.created_by
WHERE s.id = $1
`

type GetShareByIDRow struct {
	ID            uuid.UUID
	Token         string
	NodeID        uuid.UUID
	CreatedBy     uuid.UUID
	PasswordHash  *string
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	NodeName      string
	NodeKind      string
	NodeDeletedAt pgtype.Timestamptz
	OwnerDisabled bool
}

func (q *Queries) GetShareByID(ctx context.Context, id uuid.UUID) (GetShareByIDRow, error) {
	row := q.db.QueryRow(ctx, getShareByID, id)
	var i GetShareByIDRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.NodeID,
		&i.CreatedBy,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.NodeName,
		&i.NodeKind,
		&i.NodeDeletedAt,
		&i.OwnerDisabled,
	)
	return i, err
}

const getShareByToken = `-- name: GetShareByToken :one
SELECT s.id, s.token, s.node_id, s.created_by, s.password_hash, s.expires_at, s.revoked_at, s.created_at, n.name AS node_name, n.kind AS node_kind, n.deleted_at AS node_deleted_at,
       (u.disabled_at IS NOT NULL)::boolean AS owner_disabled
FROM shares s JOIN nodes n ON n.id = s.node_id JOIN users u ON u.id = s.created_by
WHERE s.token = $1
`

type GetShareByTokenRow struct {
	ID            uuid.UUID
	Token         string
	NodeID        uuid.UUID
	CreatedBy     uuid.UUID
	PasswordHash  *string
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	NodeName      string
	NodeKind      string
	NodeDeletedAt pgtype.Timestamptz
	OwnerDisabled bool
}

func (q *Queries) GetShareByToken(ctx context.Context, token string) (GetShareByTokenRow, error) {
	row := q.db.QueryRow(ctx, getShareByToken, token)
	var i GetShareByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.NodeID,
		&i.CreatedBy,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.NodeName,
		&i.NodeKind,
		&i.NodeDeletedAt,
		&i.OwnerDisabled,
	)
	return i, err
}

const listMyShares = `-- name: ListMyShares :many
SELECT s.id, s.token, s.password_hash, s.expires_at, s.created_at,
       n.id AS node_id, n.parent_id AS node_parent_id, n.name AS node_name,
       n.kind AS node_kind, n.created_at AS node_created_at, n.updated_at AS node_updated_at,
       b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256,
       COALESCE(v.verify_count, 0)::bigint   AS verify_count,
       COALESCE(v.download_count, 0)::bigint AS download_count,
       v.last_at   AS last_visit_at,
       v.last_kind AS last_visit_kind
FROM shares s
JOIN nodes n ON n.id = s.node_id
LEFT JOIN blobs b ON b.id = n.blob_id
LEFT JOIN LATERAL (
    SELECT count(*) FILTER (WHERE sv.kind = 'verify')  AS verify_count,
           count(*) FILTER (WHERE sv.kind <> 'verify') AS download_count,
           max(sv.created_at)::timestamptz             AS last_at,
           (array_agg(sv.kind ORDER BY sv.created_at DESC, sv.id DESC))[1]::text AS last_kind
    FROM share_visits sv
    WHERE sv.share_id = s.id
) v ON true
WHERE s.created_by = $1 AND s.revoked_at IS NULL AND n.deleted_at IS NULL
ORDER BY s.created_at DESC, s.id
`

type ListMySharesRow struct {
	ID            uuid.UUID
	Token         string
	PasswordHash  *string
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	NodeID        uuid.UUID
	NodeParentID  *uuid.UUID
	NodeName      string
	NodeKind      string
	NodeCreatedAt pgtype.Timestamptz
	NodeUpdatedAt pgtype.Timestamptz
	BlobSize      *int64
	BlobMime      *string
	BlobSha256    *string
	VerifyCount   int64
	DownloadCount int64
	LastVisitAt   pgtype.Timestamptz
	LastVisitKind string
}

// 顺带带出访问统计。用 LATERAL 一次扫完,别让列表变成 N+1。
// verify = 访客进入(验密成功);download 把单文件下载与打包下载合并计数。
func (q *Queries) ListMyShares(ctx context.Context, createdBy uuid.UUID) ([]ListMySharesRow, error) {
	rows, err := q.db.Query(ctx, listMyShares, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMySharesRow
	for rows.Next() {
		var i ListMySharesRow
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.PasswordHash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.NodeID,
			&i.NodeParentID,
			&i.NodeName,
			&i.NodeKind,
			&i.NodeCreatedAt,
			&i.NodeUpdatedAt,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
			&i.VerifyCount,
			&i.DownloadCount,
			&i.LastVisitAt,
			&i.LastVisitKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareVisits = `-- name: ListShareVisits :many
SELECT kind, ip, user_agent, created_at
FROM share_visits
WHERE share_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListShareVisitsParams struct {
	ShareID uuid.UUID
	Limit   int32
}

type ListShareVisitsRow struct {
	Kind      string
	Ip        *string
	UserAgent *string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListShareVisits(ctx context.Context, arg ListShareVisitsParams) ([]ListShareVisitsRow, error) {
	rows, err := q.db.Query(ctx, listShareVisits, arg.ShareID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShareVisitsRow
	for rows.Next() {
		var i ListShareVisitsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordShareVisit = `-- name: RecordShareVisit :exec
INSERT INTO share_visits (share_id, kind, ip, user_agent)
VALUES ($1, $2, $3, $4)
`

type RecordShareVisitParams struct {
	ShareID   uuid.UUID
	Kind      string
	Ip        *string
	UserAgent *string
}

// 尽力而为:埋点失败绝不能影响访客的访问,调用方只记日志。
func (q *Queries) RecordShareVisit(ctx context.Context, arg RecordShareVisitParams) error {
	_, err := q.db.Exec(ctx, recordShareVisit,
		arg.ShareID,
		arg.Kind,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const revokeShare = `-- name: RevokeShare :execrows
UPDATE shares SET revoked_at = now()
WHERE id = $1 AND created_by = $2 AND revoked_at IS NULL
`

type RevokeShareParams struct {
	ID        uuid.UUID
	CreatedBy uuid.UUID
}

func (q *Queries) RevokeShare(ctx context.Context, arg RevokeShareParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeShare, arg.ID, arg.CreatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
