// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShare = `-- name: CreateShare :one
INSERT INTO shares (id, token, node_id, created_by, password_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, token, node_id, created_by, password_hash, expires_at, revoked_at, created_at
`

type CreateShareParams struct {
	ID           uuid.UUID
	Token        string
	NodeID       uuid.UUID
	CreatedBy    uuid.UUID
	PasswordHash *string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (Share, error) {
	row := q.db.QueryRow(ctx, createShare,
		arg.ID,
		arg.Token,
		arg.NodeID,
		arg.CreatedBy,
		arg.PasswordHash,
		arg.ExpiresAt,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.NodeID,
		&i.CreatedBy,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getShareByID = `-- name: GetShareByID :one
SELECT s.id, s.token, s.node_id, s.created_by, s.password_hash, s.expires_at, s.revoked_at, s.created_at, n.name AS node_name, n.kind AS node_kind, n.deleted_at AS node_deleted_at,
       (u.disabled_at IS NOT NULL)::boolean AS owner_disabled
FROM shares s JOIN nodes n ON n.id = s.node_id JOIN users u ON u.id = s.created_by
WHERE s.id = $1
`

type GetShareByIDRow struct {
	ID            uuid.UUID
	Token         string
	NodeID        uuid.UUID
	CreatedBy     uuid.UUID
	PasswordHash  *string
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	NodeName      string
	NodeKind      string
	NodeDeletedAt pgtype.Timestamptz
	OwnerDisabled bool
}

func (q *Queries) GetShareByID(ctx context.Context, id uuid.UUID) (GetShareByIDRow, error) {
	row := q.db.QueryRow(ctx, getShareByID, id)
	var i GetShareByIDRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.NodeID,
		&i.CreatedBy,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.NodeName,
		&i.NodeKind,
		&i.NodeDeletedAt,
		&i.OwnerDisabled,
	)
	return i, err
}

const getShareByToken = `-- name: GetShareByToken :one
SELECT s.id, s.token, s.node_id, s.created_by, s.password_hash, s.expires_at, s.revoked_at, s.created_at, n.name AS node_name, n.kind AS node_kind, n.deleted_at AS node_deleted_at,
       (u.disabled_at IS NOT NULL)::boolean AS owner_disabled
FROM shares s JOIN nodes n ON n.id = s.node_id JOIN users u ON u.id = s.created_by
WHERE s.token = $1
`

type GetShareByTokenRow struct {
	ID            uuid.UUID
	Token         string
	NodeID        uuid.UUID
	CreatedBy     uuid.UUID
	PasswordHash  *string
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	NodeName      string
	NodeKind      string
	NodeDeletedAt pgtype.Timestamptz
	OwnerDisabled bool
}

func (q *Queries) GetShareByToken(ctx context.Context, token string) (GetShareByTokenRow, error) {
	row := q.db.QueryRow(ctx, getShareByToken, token)
	var i GetShareByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.NodeID,
		&i.CreatedBy,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.NodeName,
		&i.NodeKind,
		&i.NodeDeletedAt,
		&i.OwnerDisabled,
	)
	return i, err
}

const listMyShares = `-- name: ListMyShares :many
SELECT s.id, s.token, s.password_hash, s.expires_at, s.created_at,
       n.id AS node_id, n.parent_id AS node_parent_id, n.name AS node_name,
       n.kind AS node_kind, n.created_at AS node_created_at, n.updated_at AS node_updated_at,
       b.size AS blob_size, b.mime AS blob_mime, b.sha256 AS blob_sha256
FROM shares s
JOIN nodes n ON n.id = s.node_id
LEFT JOIN blobs b ON b.id = n.blob_id
WHERE s.created_by = $1 AND s.revoked_at IS NULL AND n.deleted_at IS NULL
ORDER BY s.created_at DESC, s.id
`

type ListMySharesRow struct {
	ID            uuid.UUID
	Token         string
	PasswordHash  *string
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	NodeID        uuid.UUID
	NodeParentID  *uuid.UUID
	NodeName      string
	NodeKind      string
	NodeCreatedAt pgtype.Timestamptz
	NodeUpdatedAt pgtype.Timestamptz
	BlobSize      *int64
	BlobMime      *string
	BlobSha256    *string
}

func (q *Queries) ListMyShares(ctx context.Context, createdBy uuid.UUID) ([]ListMySharesRow, error) {
	rows, err := q.db.Query(ctx, listMyShares, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMySharesRow
	for rows.Next() {
		var i ListMySharesRow
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.PasswordHash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.NodeID,
			&i.NodeParentID,
			&i.NodeName,
			&i.NodeKind,
			&i.NodeCreatedAt,
			&i.NodeUpdatedAt,
			&i.BlobSize,
			&i.BlobMime,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeShare = `-- name: RevokeShare :execrows
UPDATE shares SET revoked_at = now()
WHERE id = $1 AND created_by = $2 AND revoked_at IS NULL
`

type RevokeShareParams struct {
	ID        uuid.UUID
	CreatedBy uuid.UUID
}

func (q *Queries) RevokeShare(ctx context.Context, arg RevokeShareParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeShare, arg.ID, arg.CreatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
