// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const claimTask = `-- name: ClaimTask :one
UPDATE tasks SET status = 'running', attempts = attempts + 1, updated_at = now()
WHERE id = (
    SELECT t.id FROM tasks t
    WHERE (t.status = 'pending' OR (t.status = 'running' AND t.updated_at < now() - interval '5 minutes'))
      AND t.attempts < 3
    ORDER BY t.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, kind, blob_id, status, attempts, last_error, created_at, updated_at
`

// 单进程多 worker 抢任务;重启恢复 running 状态的滞留任务(5 分钟无更新视为死亡)
func (q *Queries) ClaimTask(ctx context.Context) (Task, error) {
	row := q.db.QueryRow(ctx, claimTask)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.BlobID,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countTasksByStatus = `-- name: CountTasksByStatus :many
SELECT status, count(*) AS count FROM tasks GROUP BY status
`

type CountTasksByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountTasksByStatus(ctx context.Context) ([]CountTasksByStatusRow, error) {
	rows, err := q.db.Query(ctx, countTasksByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTasksByStatusRow
	for rows.Next() {
		var i CountTasksByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueTask = `-- name: EnqueueTask :exec
INSERT INTO tasks (id, kind, blob_id)
VALUES ($1, $2, $3)
ON CONFLICT (kind, blob_id) DO UPDATE
SET status = 'pending', attempts = 0, last_error = NULL, updated_at = now()
WHERE tasks.status = 'failed'
`

type EnqueueTaskParams struct {
	ID     uuid.UUID
	Kind   string
	BlobID uuid.UUID
}

// 同 (kind, blob) 幂等;此前失败的终态任务重新入队(如同 hash 再次被上传)
func (q *Queries) EnqueueTask(ctx context.Context, arg EnqueueTaskParams) error {
	_, err := q.db.Exec(ctx, enqueueTask, arg.ID, arg.Kind, arg.BlobID)
	return err
}

const finishTask = `-- name: FinishTask :exec
UPDATE tasks SET status = $2, last_error = $3, updated_at = now() WHERE id = $1
`

type FinishTaskParams struct {
	ID        uuid.UUID
	Status    string
	LastError *string
}

func (q *Queries) FinishTask(ctx context.Context, arg FinishTaskParams) error {
	_, err := q.db.Exec(ctx, finishTask, arg.ID, arg.Status, arg.LastError)
	return err
}

const retryFailedTasks = `-- name: RetryFailedTasks :execrows
UPDATE tasks SET status = 'pending', attempts = 0, last_error = NULL, updated_at = now()
WHERE status = 'failed'
`

func (q *Queries) RetryFailedTasks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, retryFailedTasks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
