// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer_sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimFinalizingTransfer = `-- name: ClaimFinalizingTransfer :one
UPDATE transfer_sessions SET status = 'processing'
WHERE id = (
    SELECT id FROM transfer_sessions
    WHERE status = 'finalizing'
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, owner_id, target_parent, target_name, size, mime, expected_sha256, computed_sha256, object_key, transport, minio_upload_id, part_size, status, fail_reason, node_id, idempotency_key, created_at, expires_at
`

func (q *Queries) ClaimFinalizingTransfer(ctx context.Context) (TransferSession, error) {
	row := q.db.QueryRow(ctx, claimFinalizingTransfer)
	var i TransferSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TargetParent,
		&i.TargetName,
		&i.Size,
		&i.Mime,
		&i.ExpectedSha256,
		&i.ComputedSha256,
		&i.ObjectKey,
		&i.Transport,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.NodeID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const countActiveTransferSessions = `-- name: CountActiveTransferSessions :one
SELECT count(*) FROM transfer_sessions
WHERE owner_id = $1 AND status IN ('uploading','completing','finalizing','processing','verifying')
`

func (q *Queries) CountActiveTransferSessions(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTransferSessions, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransferSession = `-- name: CreateTransferSession :one
INSERT INTO transfer_sessions (
    id, owner_id, target_parent, target_name, size, mime, expected_sha256,
    object_key, transport, minio_upload_id, part_size, idempotency_key, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, owner_id, target_parent, target_name, size, mime, expected_sha256, computed_sha256, object_key, transport, minio_upload_id, part_size, status, fail_reason, node_id, idempotency_key, created_at, expires_at
`

type CreateTransferSessionParams struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	TargetParent   *uuid.UUID
	TargetName     string
	Size           int64
	Mime           string
	ExpectedSha256 *string
	ObjectKey      string
	Transport      string
	MinioUploadID  *string
	PartSize       int32
	IdempotencyKey *string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreateTransferSession(ctx context.Context, arg CreateTransferSessionParams) (TransferSession, error) {
	row := q.db.QueryRow(ctx, createTransferSession,
		arg.ID,
		arg.OwnerID,
		arg.TargetParent,
		arg.TargetName,
		arg.Size,
		arg.Mime,
		arg.ExpectedSha256,
		arg.ObjectKey,
		arg.Transport,
		arg.MinioUploadID,
		arg.PartSize,
		arg.IdempotencyKey,
		arg.ExpiresAt,
	)
	var i TransferSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TargetParent,
		&i.TargetName,
		&i.Size,
		&i.Mime,
		&i.ExpectedSha256,
		&i.ComputedSha256,
		&i.ObjectKey,
		&i.Transport,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.NodeID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTransferSession = `-- name: GetTransferSession :one
SELECT id, owner_id, target_parent, target_name, size, mime, expected_sha256, computed_sha256, object_key, transport, minio_upload_id, part_size, status, fail_reason, node_id, idempotency_key, created_at, expires_at FROM transfer_sessions WHERE id = $1 AND owner_id = $2
`

type GetTransferSessionParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetTransferSession(ctx context.Context, arg GetTransferSessionParams) (TransferSession, error) {
	row := q.db.QueryRow(ctx, getTransferSession, arg.ID, arg.OwnerID)
	var i TransferSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TargetParent,
		&i.TargetName,
		&i.Size,
		&i.Mime,
		&i.ExpectedSha256,
		&i.ComputedSha256,
		&i.ObjectKey,
		&i.Transport,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.NodeID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTransferSessionByIdempotencyKey = `-- name: GetTransferSessionByIdempotencyKey :one
SELECT id, owner_id, target_parent, target_name, size, mime, expected_sha256, computed_sha256, object_key, transport, minio_upload_id, part_size, status, fail_reason, node_id, idempotency_key, created_at, expires_at FROM transfer_sessions
WHERE owner_id = $1 AND idempotency_key = $2
`

type GetTransferSessionByIdempotencyKeyParams struct {
	OwnerID        uuid.UUID
	IdempotencyKey *string
}

func (q *Queries) GetTransferSessionByIdempotencyKey(ctx context.Context, arg GetTransferSessionByIdempotencyKeyParams) (TransferSession, error) {
	row := q.db.QueryRow(ctx, getTransferSessionByIdempotencyKey, arg.OwnerID, arg.IdempotencyKey)
	var i TransferSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TargetParent,
		&i.TargetName,
		&i.Size,
		&i.Mime,
		&i.ExpectedSha256,
		&i.ComputedSha256,
		&i.ObjectKey,
		&i.Transport,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.NodeID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listExpiredTransferSessions = `-- name: ListExpiredTransferSessions :many
SELECT id, owner_id, target_parent, target_name, size, mime, expected_sha256, computed_sha256, object_key, transport, minio_upload_id, part_size, status, fail_reason, node_id, idempotency_key, created_at, expires_at FROM transfer_sessions
WHERE status IN ('uploading','completing','finalizing','processing') AND expires_at < now()
LIMIT 100
`

func (q *Queries) ListExpiredTransferSessions(ctx context.Context) ([]TransferSession, error) {
	rows, err := q.db.Query(ctx, listExpiredTransferSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransferSession
	for rows.Next() {
		var i TransferSession
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.TargetParent,
			&i.TargetName,
			&i.Size,
			&i.Mime,
			&i.ExpectedSha256,
			&i.ComputedSha256,
			&i.ObjectKey,
			&i.Transport,
			&i.MinioUploadID,
			&i.PartSize,
			&i.Status,
			&i.FailReason,
			&i.NodeID,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransferAborted = `-- name: MarkTransferAborted :exec
UPDATE transfer_sessions SET status = 'aborted', fail_reason = $2
WHERE id = $1 AND owner_id = $3
`

type MarkTransferAbortedParams struct {
	ID         uuid.UUID
	FailReason *string
	OwnerID    uuid.UUID
}

func (q *Queries) MarkTransferAborted(ctx context.Context, arg MarkTransferAbortedParams) error {
	_, err := q.db.Exec(ctx, markTransferAborted, arg.ID, arg.FailReason, arg.OwnerID)
	return err
}

const markTransferCompleting = `-- name: MarkTransferCompleting :one
UPDATE transfer_sessions SET status = 'completing', fail_reason = NULL
WHERE id = $1 AND owner_id = $2 AND status = 'uploading'
RETURNING id, owner_id, target_parent, target_name, size, mime, expected_sha256, computed_sha256, object_key, transport, minio_upload_id, part_size, status, fail_reason, node_id, idempotency_key, created_at, expires_at
`

type MarkTransferCompletingParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) MarkTransferCompleting(ctx context.Context, arg MarkTransferCompletingParams) (TransferSession, error) {
	row := q.db.QueryRow(ctx, markTransferCompleting, arg.ID, arg.OwnerID)
	var i TransferSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TargetParent,
		&i.TargetName,
		&i.Size,
		&i.Mime,
		&i.ExpectedSha256,
		&i.ComputedSha256,
		&i.ObjectKey,
		&i.Transport,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.NodeID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markTransferFailed = `-- name: MarkTransferFailed :exec
UPDATE transfer_sessions SET status = 'failed', fail_reason = $2
WHERE id = $1
`

type MarkTransferFailedParams struct {
	ID         uuid.UUID
	FailReason *string
}

func (q *Queries) MarkTransferFailed(ctx context.Context, arg MarkTransferFailedParams) error {
	_, err := q.db.Exec(ctx, markTransferFailed, arg.ID, arg.FailReason)
	return err
}

const markTransferFinalizing = `-- name: MarkTransferFinalizing :one
UPDATE transfer_sessions SET status = 'finalizing', fail_reason = NULL
WHERE id = $1 AND owner_id = $2 AND status IN ('uploading','completing')
RETURNING id, owner_id, target_parent, target_name, size, mime, expected_sha256, computed_sha256, object_key, transport, minio_upload_id, part_size, status, fail_reason, node_id, idempotency_key, created_at, expires_at
`

type MarkTransferFinalizingParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) MarkTransferFinalizing(ctx context.Context, arg MarkTransferFinalizingParams) (TransferSession, error) {
	row := q.db.QueryRow(ctx, markTransferFinalizing, arg.ID, arg.OwnerID)
	var i TransferSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TargetParent,
		&i.TargetName,
		&i.Size,
		&i.Mime,
		&i.ExpectedSha256,
		&i.ComputedSha256,
		&i.ObjectKey,
		&i.Transport,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.NodeID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markTransferReady = `-- name: MarkTransferReady :exec
UPDATE transfer_sessions SET status = 'ready', fail_reason = NULL
WHERE id = $1
`

func (q *Queries) MarkTransferReady(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTransferReady, id)
	return err
}

const markTransferReadyBySha = `-- name: MarkTransferReadyBySha :exec
UPDATE transfer_sessions SET status = 'ready', fail_reason = NULL
WHERE computed_sha256 = $1 AND status = 'verifying'
`

func (q *Queries) MarkTransferReadyBySha(ctx context.Context, computedSha256 *string) error {
	_, err := q.db.Exec(ctx, markTransferReadyBySha, computedSha256)
	return err
}

const markTransferVerifying = `-- name: MarkTransferVerifying :exec
UPDATE transfer_sessions
SET status = 'verifying', computed_sha256 = $2, node_id = $3
WHERE id = $1
`

type MarkTransferVerifyingParams struct {
	ID             uuid.UUID
	ComputedSha256 *string
	NodeID         *uuid.UUID
}

func (q *Queries) MarkTransferVerifying(ctx context.Context, arg MarkTransferVerifyingParams) error {
	_, err := q.db.Exec(ctx, markTransferVerifying, arg.ID, arg.ComputedSha256, arg.NodeID)
	return err
}

const markTransfersFailedBySha = `-- name: MarkTransfersFailedBySha :exec
UPDATE transfer_sessions SET status = 'failed', fail_reason = $2
WHERE computed_sha256 = $1 AND status = 'verifying'
`

type MarkTransfersFailedByShaParams struct {
	ComputedSha256 *string
	FailReason     *string
}

func (q *Queries) MarkTransfersFailedBySha(ctx context.Context, arg MarkTransfersFailedByShaParams) error {
	_, err := q.db.Exec(ctx, markTransfersFailedBySha, arg.ComputedSha256, arg.FailReason)
	return err
}

const resetTransferUploading = `-- name: ResetTransferUploading :exec
UPDATE transfer_sessions SET status = 'uploading'
WHERE id = $1 AND owner_id = $2 AND status = 'completing'
`

type ResetTransferUploadingParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) ResetTransferUploading(ctx context.Context, arg ResetTransferUploadingParams) error {
	_, err := q.db.Exec(ctx, resetTransferUploading, arg.ID, arg.OwnerID)
	return err
}

const sumActiveTransferBytes = `-- name: SumActiveTransferBytes :one
SELECT COALESCE(sum(size), 0)::bigint FROM transfer_sessions
WHERE owner_id = $1 AND status IN ('uploading','completing','finalizing','processing','verifying')
`

func (q *Queries) SumActiveTransferBytes(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumActiveTransferBytes, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
