// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSessions = `-- name: CountActiveSessions :one
SELECT count(*) FROM upload_sessions
WHERE owner_id = $1 AND status IN ('uploading','completing','verifying')
`

func (q *Queries) CountActiveSessions(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessions, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUploadSession = `-- name: CreateUploadSession :one
INSERT INTO upload_sessions (id, owner_id, sha256, size, target_parent, target_name, minio_upload_id, part_size, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_id, sha256, size, target_parent, target_name, minio_upload_id, part_size, status, fail_reason, created_at, expires_at
`

type CreateUploadSessionParams struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Sha256        string
	Size          int64
	TargetParent  *uuid.UUID
	TargetName    string
	MinioUploadID string
	PartSize      int32
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, createUploadSession,
		arg.ID,
		arg.OwnerID,
		arg.Sha256,
		arg.Size,
		arg.TargetParent,
		arg.TargetName,
		arg.MinioUploadID,
		arg.PartSize,
		arg.ExpiresAt,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Sha256,
		&i.Size,
		&i.TargetParent,
		&i.TargetName,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT id, owner_id, sha256, size, target_parent, target_name, minio_upload_id, part_size, status, fail_reason, created_at, expires_at FROM upload_sessions WHERE id = $1 AND owner_id = $2
`

type GetUploadSessionParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetUploadSession(ctx context.Context, arg GetUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSession, arg.ID, arg.OwnerID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Sha256,
		&i.Size,
		&i.TargetParent,
		&i.TargetName,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listExpiredSessions = `-- name: ListExpiredSessions :many
SELECT id, owner_id, sha256, size, target_parent, target_name, minio_upload_id, part_size, status, fail_reason, created_at, expires_at FROM upload_sessions
WHERE status = 'uploading' AND expires_at < now()
LIMIT 100
`

func (q *Queries) ListExpiredSessions(ctx context.Context) ([]UploadSession, error) {
	rows, err := q.db.Query(ctx, listExpiredSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadSession
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Sha256,
			&i.Size,
			&i.TargetParent,
			&i.TargetName,
			&i.MinioUploadID,
			&i.PartSize,
			&i.Status,
			&i.FailReason,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionsVerifyResult = `-- name: MarkSessionsVerifyResult :exec
UPDATE upload_sessions SET status = $2, fail_reason = $3
WHERE sha256 = $1 AND status = 'verifying'
`

type MarkSessionsVerifyResultParams struct {
	Sha256     string
	Status     string
	FailReason *string
}

// hash 校验结束后,把该 blob 上所有 verifying 会话标成终态
func (q *Queries) MarkSessionsVerifyResult(ctx context.Context, arg MarkSessionsVerifyResultParams) error {
	_, err := q.db.Exec(ctx, markSessionsVerifyResult, arg.Sha256, arg.Status, arg.FailReason)
	return err
}

const setUploadSessionStatus = `-- name: SetUploadSessionStatus :exec
UPDATE upload_sessions SET status = $3, fail_reason = $4
WHERE id = $1 AND owner_id = $2
`

type SetUploadSessionStatusParams struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	Status     string
	FailReason *string
}

func (q *Queries) SetUploadSessionStatus(ctx context.Context, arg SetUploadSessionStatusParams) error {
	_, err := q.db.Exec(ctx, setUploadSessionStatus,
		arg.ID,
		arg.OwnerID,
		arg.Status,
		arg.FailReason,
	)
	return err
}
