// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimCompletingUpload = `-- name: ClaimCompletingUpload :one
SELECT id, owner_id, sha256, size, target_parent, target_name, minio_upload_id, part_size, status, fail_reason, created_at, expires_at, object_key, node_id, fail_code FROM upload_sessions
WHERE status = 'completing' AND object_key IS NOT NULL AND expires_at > now()
ORDER BY created_at
LIMIT 1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimCompletingUpload(ctx context.Context) (UploadSession, error) {
	row := q.db.QueryRow(ctx, claimCompletingUpload)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Sha256,
		&i.Size,
		&i.TargetParent,
		&i.TargetName,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ObjectKey,
		&i.NodeID,
		&i.FailCode,
	)
	return i, err
}

const clearUploadObjectKey = `-- name: ClearUploadObjectKey :exec
UPDATE upload_sessions SET object_key = NULL WHERE id = $1
`

func (q *Queries) ClearUploadObjectKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUploadObjectKey, id)
	return err
}

const countActiveSessions = `-- name: CountActiveSessions :one
SELECT count(*) FROM upload_sessions
WHERE owner_id = $1 AND status IN ('uploading','completing','verifying')
`

func (q *Queries) CountActiveSessions(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessions, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUploadSession = `-- name: CreateUploadSession :one
INSERT INTO upload_sessions (id, owner_id, sha256, size, target_parent, target_name, minio_upload_id, part_size, expires_at, object_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, owner_id, sha256, size, target_parent, target_name, minio_upload_id, part_size, status, fail_reason, created_at, expires_at, object_key, node_id, fail_code
`

type CreateUploadSessionParams struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Sha256        string
	Size          int64
	TargetParent  *uuid.UUID
	TargetName    string
	MinioUploadID string
	PartSize      int32
	ExpiresAt     pgtype.Timestamptz
	ObjectKey     *string
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, createUploadSession,
		arg.ID,
		arg.OwnerID,
		arg.Sha256,
		arg.Size,
		arg.TargetParent,
		arg.TargetName,
		arg.MinioUploadID,
		arg.PartSize,
		arg.ExpiresAt,
		arg.ObjectKey,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Sha256,
		&i.Size,
		&i.TargetParent,
		&i.TargetName,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ObjectKey,
		&i.NodeID,
		&i.FailCode,
	)
	return i, err
}

const failUploadSession = `-- name: FailUploadSession :exec
UPDATE upload_sessions SET status = 'failed', fail_code = $2, fail_reason = $3
WHERE id = $1
`

type FailUploadSessionParams struct {
	ID         uuid.UUID
	FailCode   *string
	FailReason *string
}

func (q *Queries) FailUploadSession(ctx context.Context, arg FailUploadSessionParams) error {
	_, err := q.db.Exec(ctx, failUploadSession, arg.ID, arg.FailCode, arg.FailReason)
	return err
}

const finishUploadSession = `-- name: FinishUploadSession :exec
UPDATE upload_sessions SET status = 'done', node_id = $2, fail_reason = NULL, fail_code = NULL
WHERE id = $1
`

type FinishUploadSessionParams struct {
	ID     uuid.UUID
	NodeID *uuid.UUID
}

func (q *Queries) FinishUploadSession(ctx context.Context, arg FinishUploadSessionParams) error {
	_, err := q.db.Exec(ctx, finishUploadSession, arg.ID, arg.NodeID)
	return err
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT id, owner_id, sha256, size, target_parent, target_name, minio_upload_id, part_size, status, fail_reason, created_at, expires_at, object_key, node_id, fail_code FROM upload_sessions WHERE id = $1 AND owner_id = $2
`

type GetUploadSessionParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetUploadSession(ctx context.Context, arg GetUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSession, arg.ID, arg.OwnerID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Sha256,
		&i.Size,
		&i.TargetParent,
		&i.TargetName,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ObjectKey,
		&i.NodeID,
		&i.FailCode,
	)
	return i, err
}

const getUploadSessionForUpdate = `-- name: GetUploadSessionForUpdate :one
SELECT id, owner_id, sha256, size, target_parent, target_name, minio_upload_id, part_size, status, fail_reason, created_at, expires_at, object_key, node_id, fail_code FROM upload_sessions WHERE id = $1 AND owner_id = $2 FOR UPDATE
`

type GetUploadSessionForUpdateParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetUploadSessionForUpdate(ctx context.Context, arg GetUploadSessionForUpdateParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSessionForUpdate, arg.ID, arg.OwnerID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Sha256,
		&i.Size,
		&i.TargetParent,
		&i.TargetName,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ObjectKey,
		&i.NodeID,
		&i.FailCode,
	)
	return i, err
}

const listExpiredSessions = `-- name: ListExpiredSessions :many
SELECT id, owner_id, sha256, size, target_parent, target_name, minio_upload_id, part_size, status, fail_reason, created_at, expires_at, object_key, node_id, fail_code FROM upload_sessions
WHERE (status IN ('uploading', 'completing') OR object_key IS NOT NULL) AND expires_at < now()
LIMIT 100
`

func (q *Queries) ListExpiredSessions(ctx context.Context) ([]UploadSession, error) {
	rows, err := q.db.Query(ctx, listExpiredSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadSession
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Sha256,
			&i.Size,
			&i.TargetParent,
			&i.TargetName,
			&i.MinioUploadID,
			&i.PartSize,
			&i.Status,
			&i.FailReason,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ObjectKey,
			&i.NodeID,
			&i.FailCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionsVerifyResult = `-- name: MarkSessionsVerifyResult :exec
UPDATE upload_sessions SET status = $2, fail_reason = $3
WHERE sha256 = $1 AND status = 'verifying'
`

type MarkSessionsVerifyResultParams struct {
	Sha256     string
	Status     string
	FailReason *string
}

// hash 校验结束后,把该 blob 上所有 verifying 会话标成终态
func (q *Queries) MarkSessionsVerifyResult(ctx context.Context, arg MarkSessionsVerifyResultParams) error {
	_, err := q.db.Exec(ctx, markSessionsVerifyResult, arg.Sha256, arg.Status, arg.FailReason)
	return err
}

const setUploadSessionStatus = `-- name: SetUploadSessionStatus :exec
UPDATE upload_sessions SET status = $3, fail_reason = $4
WHERE id = $1 AND owner_id = $2
`

type SetUploadSessionStatusParams struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	Status     string
	FailReason *string
}

func (q *Queries) SetUploadSessionStatus(ctx context.Context, arg SetUploadSessionStatusParams) error {
	_, err := q.db.Exec(ctx, setUploadSessionStatus,
		arg.ID,
		arg.OwnerID,
		arg.Status,
		arg.FailReason,
	)
	return err
}

const tryLockUploadSession = `-- name: TryLockUploadSession :one
SELECT id, owner_id, sha256, size, target_parent, target_name, minio_upload_id, part_size, status, fail_reason, created_at, expires_at, object_key, node_id, fail_code FROM upload_sessions WHERE id = $1 AND owner_id = $2 FOR UPDATE NOWAIT
`

type TryLockUploadSessionParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) TryLockUploadSession(ctx context.Context, arg TryLockUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, tryLockUploadSession, arg.ID, arg.OwnerID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Sha256,
		&i.Size,
		&i.TargetParent,
		&i.TargetName,
		&i.MinioUploadID,
		&i.PartSize,
		&i.Status,
		&i.FailReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ObjectKey,
		&i.NodeID,
		&i.FailCode,
	)
	return i, err
}
