// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AdminOverview struct {
	UserCount      int          `json:"userCount"`
	TotalUsedBytes int64        `json:"totalUsedBytes"`
	BlobCount      int          `json:"blobCount"`
	BlobBytes      int64        `json:"blobBytes"`
	TaskCounts     []*TaskCount `json:"taskCounts"`
}

type AdminUser struct {
	ID         string    `json:"id"`
	Username   string    `json:"username"`
	IsAdmin    bool      `json:"isAdmin"`
	Disabled   bool      `json:"disabled"`
	QuotaBytes int64     `json:"quotaBytes"`
	UsedBytes  int64     `json:"usedBytes"`
	CreatedAt  time.Time `json:"createdAt"`
}

type AuthPayload struct {
	AccessToken string `json:"accessToken"`
	User        *User  `json:"user"`
}

type Mutation struct {
}

type Node struct {
	ID           string       `json:"id"`
	ParentID     *string      `json:"parentId,omitempty"`
	Name         string       `json:"name"`
	Kind         NodeKind     `json:"kind"`
	Size         *int64       `json:"size,omitempty"`
	Mime         *string      `json:"mime,omitempty"`
	Sha256       *string      `json:"sha256,omitempty"`
	CreatedAt    time.Time    `json:"createdAt"`
	UpdatedAt    time.Time    `json:"updatedAt"`
	DeletedAt    *time.Time   `json:"deletedAt,omitempty"`
	Preview      *PreviewInfo `json:"preview"`
	DownloadURL  *string      `json:"downloadUrl,omitempty"`
	SubtreeBytes *int64       `json:"subtreeBytes,omitempty"`
	SubtreeCount *int64       `json:"subtreeCount,omitempty"`
	StatsStale   *bool        `json:"statsStale,omitempty"`
	// 由列表转换器置位:preview 走零查询乐观路径
	InList bool `json:"-"`
}

type NodePage struct {
	Items      []*Node `json:"items"`
	NextCursor *string `json:"nextCursor,omitempty"`
	Total      int     `json:"total"`
}

type PartEtag struct {
	PartNumber int    `json:"partNumber"`
	Etag       string `json:"etag"`
}

type PartURL struct {
	PartNumber int    `json:"partNumber"`
	URL        string `json:"url"`
}

type PreviewInfo struct {
	Kind        PreviewKind `json:"kind"`
	ThumbURL    *string     `json:"thumbUrl,omitempty"`
	LargeURL    *string     `json:"largeUrl,omitempty"`
	ContentURL  *string     `json:"contentUrl,omitempty"`
	Status      *TaskStatus `json:"status,omitempty"`
	DurationSec *int        `json:"durationSec,omitempty"`
}

type Query struct {
}

type Share struct {
	ID          string     `json:"id"`
	Token       string     `json:"token"`
	Node        *Node      `json:"node"`
	HasPassword bool       `json:"hasPassword"`
	ExpiresAt   *time.Time `json:"expiresAt,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
}

type ShareAuth struct {
	AccessToken string `json:"accessToken"`
}

type ShareInfo struct {
	Token        string   `json:"token"`
	Name         string   `json:"name"`
	Kind         NodeKind `json:"kind"`
	NeedPassword bool     `json:"needPassword"`
	Expired      bool     `json:"expired"`
}

type TaskCount struct {
	Status string `json:"status"`
	Count  int    `json:"count"`
}

type UploadInit struct {
	Instant bool           `json:"instant"`
	Node    *Node          `json:"node,omitempty"`
	Session *UploadSession `json:"session,omitempty"`
}

type UploadSession struct {
	ID            string     `json:"id"`
	PartSize      int        `json:"partSize"`
	PartUrls      []*PartURL `json:"partUrls"`
	UploadedParts []int      `json:"uploadedParts"`
	ExpiresAt     time.Time  `json:"expiresAt"`
	Status        string     `json:"status"`
}

type User struct {
	ID         string `json:"id"`
	Username   string `json:"username"`
	QuotaBytes int64  `json:"quotaBytes"`
	UsedBytes  int64  `json:"usedBytes"`
	IsAdmin    bool   `json:"isAdmin"`
}

type NodeKind string

const (
	NodeKindFile   NodeKind = "FILE"
	NodeKindFolder NodeKind = "FOLDER"
)

var AllNodeKind = []NodeKind{
	NodeKindFile,
	NodeKindFolder,
}

func (e NodeKind) IsValid() bool {
	switch e {
	case NodeKindFile, NodeKindFolder:
		return true
	}
	return false
}

func (e NodeKind) String() string {
	return string(e)
}

func (e *NodeKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeKind", str)
	}
	return nil
}

func (e NodeKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NodeKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NodeKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NodeOrder string

const (
	NodeOrderName      NodeOrder = "NAME"
	NodeOrderSize      NodeOrder = "SIZE"
	NodeOrderUpdatedAt NodeOrder = "UPDATED_AT"
)

var AllNodeOrder = []NodeOrder{
	NodeOrderName,
	NodeOrderSize,
	NodeOrderUpdatedAt,
}

func (e NodeOrder) IsValid() bool {
	switch e {
	case NodeOrderName, NodeOrderSize, NodeOrderUpdatedAt:
		return true
	}
	return false
}

func (e NodeOrder) String() string {
	return string(e)
}

func (e *NodeOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeOrder", str)
	}
	return nil
}

func (e NodeOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NodeOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NodeOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PreviewKind string

const (
	PreviewKindNone      PreviewKind = "NONE"
	PreviewKindImage     PreviewKind = "IMAGE"
	PreviewKindPDF       PreviewKind = "PDF"
	PreviewKindNativePDF PreviewKind = "NATIVE_PDF"
	PreviewKindVideo     PreviewKind = "VIDEO"
	PreviewKindAudio     PreviewKind = "AUDIO"
	PreviewKindText      PreviewKind = "TEXT"
	PreviewKindOffice    PreviewKind = "OFFICE"
)

var AllPreviewKind = []PreviewKind{
	PreviewKindNone,
	PreviewKindImage,
	PreviewKindPDF,
	PreviewKindNativePDF,
	PreviewKindVideo,
	PreviewKindAudio,
	PreviewKindText,
	PreviewKindOffice,
}

func (e PreviewKind) IsValid() bool {
	switch e {
	case PreviewKindNone, PreviewKindImage, PreviewKindPDF, PreviewKindNativePDF, PreviewKindVideo, PreviewKindAudio, PreviewKindText, PreviewKindOffice:
		return true
	}
	return false
}

func (e PreviewKind) String() string {
	return string(e)
}

func (e *PreviewKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PreviewKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PreviewKind", str)
	}
	return nil
}

func (e PreviewKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PreviewKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PreviewKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskStatus string

const (
	TaskStatusPending     TaskStatus = "PENDING"
	TaskStatusRunning     TaskStatus = "RUNNING"
	TaskStatusDone        TaskStatus = "DONE"
	TaskStatusFailed      TaskStatus = "FAILED"
	TaskStatusUnavailable TaskStatus = "UNAVAILABLE"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusPending,
	TaskStatusRunning,
	TaskStatusDone,
	TaskStatusFailed,
	TaskStatusUnavailable,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusPending, TaskStatusRunning, TaskStatusDone, TaskStatusFailed, TaskStatusUnavailable:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
