package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"time"

	"github.com/yophon/gopan/server/internal/httpx"
	"github.com/yophon/gopan/server/internal/service"
	"github.com/yophon/gopan/server/internal/store"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, password string) (*AuthPayload, error) {
	res, err := r.Auth.Register(ctx, username, password, httpx.ClientIP(ctx))
	if err != nil {
		return nil, err
	}
	httpx.SetRefreshCookie(ctx, res.RefreshToken, int(r.Cfg.RefreshTTL.Seconds()), !r.Cfg.DevMode)
	return gqlAuth(res), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*AuthPayload, error) {
	res, err := r.Auth.Login(ctx, username, password, httpx.ClientIP(ctx))
	if err != nil {
		return nil, err
	}
	httpx.SetRefreshCookie(ctx, res.RefreshToken, int(r.Cfg.RefreshTTL.Seconds()), !r.Cfg.DevMode)
	return gqlAuth(res), nil
}

// Refresh is the resolver for the refresh field.
func (r *mutationResolver) Refresh(ctx context.Context) (*AuthPayload, error) {
	res, err := r.Auth.Refresh(ctx, httpx.RefreshTokenFrom(ctx))
	if err != nil {
		httpx.ClearRefreshCookie(ctx, !r.Cfg.DevMode)
		return nil, err
	}
	httpx.SetRefreshCookie(ctx, res.RefreshToken, int(r.Cfg.RefreshTTL.Seconds()), !r.Cfg.DevMode)
	return gqlAuth(res), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	err := r.Auth.Logout(ctx, httpx.RefreshTokenFrom(ctx))
	httpx.ClearRefreshCookie(ctx, !r.Cfg.DevMode)
	return err == nil, err
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, oldPassword string, newPassword string) (*AuthPayload, error) {
	ident, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.Auth.ChangePassword(ctx, ident.UserID, oldPassword, newPassword, httpx.ClientIP(ctx))
	if err != nil {
		return nil, err
	}
	httpx.SetRefreshCookie(ctx, res.RefreshToken, int(r.Cfg.RefreshTTL.Seconds()), !r.Cfg.DevMode)
	return gqlAuth(res), nil
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, parentID *string, name string) (*Node, error) {
	id, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	pid, err := parseIDPtr(parentID)
	if err != nil {
		return nil, err
	}
	n, err := r.Nodes.CreateFolder(ctx, id.UserID, pid, name)
	if err != nil {
		return nil, err
	}
	return gqlNode(n), nil
}

// RenameNode is the resolver for the renameNode field.
func (r *mutationResolver) RenameNode(ctx context.Context, id string, name string) (*Node, error) {
	ident, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	nid, err := parseID(id)
	if err != nil {
		return nil, err
	}
	n, err := r.Nodes.Rename(ctx, ident.UserID, nid, name)
	if err != nil {
		return nil, err
	}
	return gqlNode(n), nil
}

// MoveNodes is the resolver for the moveNodes field.
func (r *mutationResolver) MoveNodes(ctx context.Context, ids []string, targetParentID *string) ([]*Node, error) {
	id, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	nids, err := parseIDs(ids)
	if err != nil {
		return nil, err
	}
	target, err := parseIDPtr(targetParentID)
	if err != nil {
		return nil, err
	}
	moved, err := r.Nodes.Move(ctx, id.UserID, nids, target)
	if err != nil {
		return nil, err
	}
	out := make([]*Node, 0, len(moved))
	for _, n := range moved {
		out = append(out, gqlNode(n))
	}
	return out, nil
}

// CopyNodes is the resolver for the copyNodes field.
func (r *mutationResolver) CopyNodes(ctx context.Context, ids []string, targetParentID *string) ([]*Node, error) {
	ident, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	nids, err := parseIDs(ids)
	if err != nil {
		return nil, err
	}
	target, err := parseIDPtr(targetParentID)
	if err != nil {
		return nil, err
	}
	copied, err := r.Nodes.Copy(ctx, ident.UserID, nids, target)
	if err != nil {
		return nil, err
	}
	out := make([]*Node, 0, len(copied))
	for _, n := range copied {
		out = append(out, gqlNode(n))
	}
	return out, nil
}

// DeleteNodes is the resolver for the deleteNodes field.
func (r *mutationResolver) DeleteNodes(ctx context.Context, ids []string) (bool, error) {
	id, err := httpx.UserFrom(ctx)
	if err != nil {
		return false, err
	}
	nids, err := parseIDs(ids)
	if err != nil {
		return false, err
	}
	if err := r.Nodes.Delete(ctx, id.UserID, nids); err != nil {
		return false, err
	}
	return true, nil
}

// RestoreNodes is the resolver for the restoreNodes field.
func (r *mutationResolver) RestoreNodes(ctx context.Context, ids []string) ([]*Node, error) {
	id, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	nids, err := parseIDs(ids)
	if err != nil {
		return nil, err
	}
	restored, err := r.Nodes.Restore(ctx, id.UserID, nids)
	if err != nil {
		return nil, err
	}
	out := make([]*Node, 0, len(restored))
	for _, n := range restored {
		out = append(out, gqlNode(n))
	}
	return out, nil
}

// PurgeNodes is the resolver for the purgeNodes field.
func (r *mutationResolver) PurgeNodes(ctx context.Context, ids []string) (bool, error) {
	id, err := httpx.UserFrom(ctx)
	if err != nil {
		return false, err
	}
	nids, err := parseIDs(ids)
	if err != nil {
		return false, err
	}
	if err := r.Nodes.Purge(ctx, id.UserID, nids); err != nil {
		return false, err
	}
	return true, nil
}

// PurgeTrash is the resolver for the purgeTrash field.
func (r *mutationResolver) PurgeTrash(ctx context.Context) (bool, error) {
	id, err := httpx.UserFrom(ctx)
	if err != nil {
		return false, err
	}
	if err := r.Nodes.PurgeTrash(ctx, id.UserID); err != nil {
		return false, err
	}
	return true, nil
}

// InitUpload is the resolver for the initUpload field.
func (r *mutationResolver) InitUpload(ctx context.Context, parentID *string, name string, sha256 string, size int64) (*UploadInit, error) {
	ident, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	pid, err := parseIDPtr(parentID)
	if err != nil {
		return nil, err
	}
	res, err := r.Uploads.Init(ctx, ident.UserID, pid, name, sha256, size)
	if err != nil {
		return nil, err
	}
	out := &UploadInit{Instant: res.Instant}
	if res.Node != nil {
		out.Node = gqlNode(*res.Node)
	}
	if res.Session != nil {
		out.Session = gqlSession(res.Session)
	}
	return out, nil
}

// CompleteUpload is the resolver for the completeUpload field.
func (r *mutationResolver) CompleteUpload(ctx context.Context, sessionID string, etags []*PartEtag) (*Node, error) {
	ident, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	sid, err := parseID(sessionID)
	if err != nil {
		return nil, err
	}
	tags := make(map[int]string, len(etags))
	for _, e := range etags {
		tags[e.PartNumber] = e.Etag
	}
	n, err := r.Uploads.Complete(ctx, ident.UserID, sid, tags)
	if err != nil {
		return nil, err
	}
	return r.getNodeFull(ctx, ident.UserID, n.ID)
}

// AbortUpload is the resolver for the abortUpload field.
func (r *mutationResolver) AbortUpload(ctx context.Context, sessionID string) (bool, error) {
	ident, err := httpx.UserFrom(ctx)
	if err != nil {
		return false, err
	}
	sid, err := parseID(sessionID)
	if err != nil {
		return false, err
	}
	if err := r.Uploads.Abort(ctx, ident.UserID, sid); err != nil {
		return false, err
	}
	return true, nil
}

// RequestPreview is the resolver for the requestPreview field.
func (r *mutationResolver) RequestPreview(ctx context.Context, nodeID string) (*PreviewInfo, error) {
	ident, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	nid, err := parseID(nodeID)
	if err != nil {
		return nil, err
	}
	info, err := r.Previews.Request(ctx, ident.UserID, nid)
	if err != nil {
		return nil, err
	}
	return gqlPreview(info), nil
}

// CreateShare is the resolver for the createShare field.
func (r *mutationResolver) CreateShare(ctx context.Context, nodeID string, password *string, expiresAt *time.Time) (*Share, error) {
	ident, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	nid, err := parseID(nodeID)
	if err != nil {
		return nil, err
	}
	sh, err := r.Shares.Create(ctx, ident.UserID, nid, password, expiresAt)
	if err != nil {
		return nil, err
	}
	node, err := r.getNodeFull(ctx, ident.UserID, sh.NodeID)
	if err != nil {
		return nil, err
	}
	out := &Share{
		ID: sh.ID.String(), Token: sh.Token, Node: node,
		HasPassword: sh.PasswordHash != nil, CreatedAt: sh.CreatedAt.Time,
	}
	if sh.ExpiresAt.Valid {
		t := sh.ExpiresAt.Time
		out.ExpiresAt = &t
	}
	return out, nil
}

// RevokeShare is the resolver for the revokeShare field.
func (r *mutationResolver) RevokeShare(ctx context.Context, id string) (bool, error) {
	ident, err := httpx.UserFrom(ctx)
	if err != nil {
		return false, err
	}
	sid, err := parseID(id)
	if err != nil {
		return false, err
	}
	if err := r.Shares.Revoke(ctx, ident.UserID, sid); err != nil {
		return false, err
	}
	return true, nil
}

// VerifySharePassword is the resolver for the verifySharePassword field.
func (r *mutationResolver) VerifySharePassword(ctx context.Context, token string, password string) (*ShareAuth, error) {
	access, err := r.Shares.Access(ctx, token, password, httpx.ClientIP(ctx))
	if err != nil {
		return nil, err
	}
	return &ShareAuth{AccessToken: access}, nil
}

// Preview is the resolver for the preview field.
func (r *nodeResolver) Preview(ctx context.Context, obj *Node) (*PreviewInfo, error) {
	if obj.Kind != NodeKindFile {
		return &PreviewInfo{Kind: PreviewKindNone}, nil
	}
	// 列表路径零查询(缩略图乐观签发);详情由单节点查询走 ForNode
	if obj.InList {
		return gqlPreview(r.Previews.ForList(ctx, obj.Name, obj.Sha256, obj.Mime, obj.Size)), nil
	}
	info, err := r.Previews.ForNode(ctx, obj.Name, obj.Sha256, obj.Mime, obj.Size)
	if err != nil {
		return nil, err
	}
	return gqlPreview(info), nil
}

// DownloadURL is the resolver for the downloadUrl field.
func (r *nodeResolver) DownloadURL(ctx context.Context, obj *Node) (*string, error) {
	if obj.Kind != NodeKindFile || obj.DeletedAt != nil {
		return nil, nil
	}
	nid, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	ident, err := r.requireNodeAccess(ctx, nid)
	if err != nil {
		return nil, err
	}
	u, err := r.Uploads.DownloadURL(ctx, ident.UserID, nid)
	if err != nil {
		return nil, err
	}
	return &u, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	id, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	u, err := r.Auth.GetUser(ctx, id.UserID)
	if err != nil {
		return nil, err
	}
	return gqlUser(u), nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (*Node, error) {
	nid, err := parseID(id)
	if err != nil {
		return nil, err
	}
	ident, err := r.requireNodeAccess(ctx, nid)
	if err != nil {
		return nil, err
	}
	return r.getNodeFull(ctx, ident.UserID, nid)
}

// Children is the resolver for the children field.
func (r *queryResolver) Children(ctx context.Context, parentID *string, cursor *string, order *NodeOrder, desc *bool) (*NodePage, error) {
	pid, err := parseIDPtr(parentID)
	if err != nil {
		return nil, err
	}
	id, err := httpx.IdentityFrom(ctx)
	if err != nil {
		return nil, err
	}
	if id.Scope != service.ScopeUser {
		// 访客不允许列根目录,只能从分享根往下走
		if pid == nil {
			return nil, service.ErrForbidden
		}
		if err := r.Shares.Authorize(ctx, id, *pid); err != nil {
			return nil, err
		}
	}
	ord := NodeOrderName
	if order != nil {
		ord = *order
	}
	descending := desc != nil && *desc
	page, err := r.Nodes.Children(ctx, id.UserID, pid, cursor, string(ord), descending)
	if err != nil {
		return nil, err
	}
	return gqlPage(page, func(row store.ListChildrenRow) *Node {
		return gqlNodeRow(nodeRow{Node: store.Node{
			ID: row.ID, OwnerID: row.OwnerID, ParentID: row.ParentID, Name: row.Name,
			Kind: row.Kind, BlobID: row.BlobID, DeletedAt: row.DeletedAt,
			CreatedAt: row.CreatedAt, UpdatedAt: row.UpdatedAt,
		}, BlobSize: row.BlobSize, BlobMime: row.BlobMime, BlobSha256: row.BlobSha256})
	}), nil
}

// SearchNodes is the resolver for the searchNodes field.
func (r *queryResolver) SearchNodes(ctx context.Context, q string, cursor *string) (*NodePage, error) {
	id, err := httpx.IdentityFrom(ctx)
	if err != nil {
		return nil, err
	}
	if id.Scope != service.ScopeUser {
		// 访客搜索限定在分享子树内
		sh, err := r.Shares.ValidateScope(ctx, id)
		if err != nil {
			return nil, err
		}
		page, err := r.Nodes.SearchInSubtree(ctx, sh.NodeID, q, cursor)
		if err != nil {
			return nil, err
		}
		return gqlPage(page, func(row store.SearchNodesInSubtreeRow) *Node {
			return gqlNodeRow(nodeRow{Node: store.Node{
				ID: row.ID, OwnerID: row.OwnerID, ParentID: row.ParentID, Name: row.Name,
				Kind: row.Kind, BlobID: row.BlobID, DeletedAt: row.DeletedAt,
				CreatedAt: row.CreatedAt, UpdatedAt: row.UpdatedAt,
			}, BlobSize: row.BlobSize, BlobMime: row.BlobMime, BlobSha256: row.BlobSha256})
		}), nil
	}
	page, err := r.Nodes.Search(ctx, id.UserID, q, cursor)
	if err != nil {
		return nil, err
	}
	return gqlPage(page, func(row store.SearchNodesRow) *Node {
		return gqlNodeRow(nodeRow{Node: store.Node{
			ID: row.ID, OwnerID: row.OwnerID, ParentID: row.ParentID, Name: row.Name,
			Kind: row.Kind, BlobID: row.BlobID, DeletedAt: row.DeletedAt,
			CreatedAt: row.CreatedAt, UpdatedAt: row.UpdatedAt,
		}, BlobSize: row.BlobSize, BlobMime: row.BlobMime, BlobSha256: row.BlobSha256})
	}), nil
}

// Trash is the resolver for the trash field.
func (r *queryResolver) Trash(ctx context.Context, cursor *string) (*NodePage, error) {
	id, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	page, err := r.Nodes.Trash(ctx, id.UserID, cursor)
	if err != nil {
		return nil, err
	}
	return gqlPage(page, func(row store.ListTrashRow) *Node {
		return gqlNodeRow(nodeRow{Node: store.Node{
			ID: row.ID, OwnerID: row.OwnerID, ParentID: row.ParentID, Name: row.Name,
			Kind: row.Kind, BlobID: row.BlobID, DeletedAt: row.DeletedAt,
			CreatedAt: row.CreatedAt, UpdatedAt: row.UpdatedAt,
		}, BlobSize: row.BlobSize, BlobMime: row.BlobMime, BlobSha256: row.BlobSha256})
	}), nil
}

// MyShares is the resolver for the myShares field.
func (r *queryResolver) MyShares(ctx context.Context) ([]*Share, error) {
	ident, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := r.Shares.List(ctx, ident.UserID)
	if err != nil {
		return nil, err
	}
	out := make([]*Share, 0, len(rows))
	for _, row := range rows {
		out = append(out, gqlShare(row))
	}
	return out, nil
}

// UploadSession is the resolver for the uploadSession field.
func (r *queryResolver) UploadSession(ctx context.Context, id string) (*UploadSession, error) {
	ident, err := httpx.UserFrom(ctx)
	if err != nil {
		return nil, err
	}
	sid, err := parseID(id)
	if err != nil {
		return nil, err
	}
	view, err := r.Uploads.Session(ctx, ident.UserID, sid)
	if err != nil {
		return nil, err
	}
	return gqlSession(view), nil
}

// ShareInfo is the resolver for the shareInfo field.
func (r *queryResolver) ShareInfo(ctx context.Context, token string) (*ShareInfo, error) {
	info, err := r.Shares.Info(ctx, token)
	if err != nil {
		return nil, err
	}
	return &ShareInfo{
		Token: info.Token, Name: info.Name,
		Kind:         NodeKind(map[string]string{"file": "FILE", "folder": "FOLDER"}[info.Kind]),
		NeedPassword: info.NeedPassword, Expired: info.Expired,
	}, nil
}

// ShareRoot is the resolver for the shareRoot field.
func (r *queryResolver) ShareRoot(ctx context.Context) (*Node, error) {
	ident, err := httpx.IdentityFrom(ctx)
	if err != nil {
		return nil, err
	}
	sh, err := r.Shares.ValidateScope(ctx, ident)
	if err != nil {
		return nil, err
	}
	node, err := r.getNodeFull(ctx, ident.UserID, sh.NodeID)
	if err != nil {
		return nil, err
	}
	node.ParentID = nil // 分享根之上的结构不暴露给访客
	return node, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Node returns NodeResolver implementation.
func (r *Resolver) Node() NodeResolver { return &nodeResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	nodeResolver     struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
